### ISSUE TITLE
userdata.js in the web folder in gofbot is written to in the wrong format. 

### ISSUE THREAD

**Issue by noxonnor** [PokemonGoF/PokemonGo-Bot-Desktop#103]
I have to reset the userdata.js file every time i restart the desktop app because of this.

**Comment by Outpox** [comment]
Could you post the content of your `userdata.js` before you have to clear it?

**Comment by noxonnor** [comment]
var users = ["myemail@gmail.com"];
var userZoom = true;
var userFollow = true;
var imageExt = ".png";
var gMapsAPIKey = "myapikey";

i need to replace it with:

var userInfo = {
    users: ["myemail@gmail.com"],
    userZoom: true,
    zoom: 16,
    userFollow: true,
    gMapsAPIKey: "myapikey"
};

Every time i start the bot via npm start. 

I've updated the bot completely. The info in the email and the apikey is whatever i put into the desktop frontend.

**Comment by Outpox** [comment]
Thanks, I'll look into it ;)

**Comment by Outpox** [comment]
Could you try with the commit in my fork? (Just above this message or [here](https://github.com/Outpox/PokemonGo-Bot-Desktop/tree/fix-103))

**Comment by noxonnor** [comment]
I don't know why, but the desktop gui became blank when used your main.js version. 

And its not writing the config right still - it's missing the : after each var.

**Comment by Outpox** [comment]
You can re-pull my branch [here](https://github.com/Outpox/PokemonGo-Bot-Desktop/tree/fix-103) fixed that dumb mistake.  
As for the blank screen, I've got no issue here :|

**Comment by noxonnor** [comment]
I can confirm that the userdata file is now correctly generated.

**Comment by Outpox** [comment]
Thanks for your feedback!
