### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by checkplys** [PokemonGoF/PokemonGo-Bot-Desktop#105]
![image](https://cloud.githubusercontent.com/assets/9268058/17562860/af3d9ae4-5f24-11e6-9594-854b029db218.png)

**Comment by checkplys** [comment]
Oh, wait I found the issue. I was using encrypt.dll 64 bit, and you need the 32 one

**Comment by ShadowZeroX** [comment]
And where you can find the 32 bits one?

**Comment by ShadowZeroX** [comment]
Or even the 64

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
