### ISSUE TITLE
Hatch multiple eggs

### ISSUE THREAD

**Issue by itsfolf** [PokemonGoF/PokemonGo-Bot-Desktop#106]
Can you add a feature to use all the incubators you have and hatch multiple eggs at the same time?

**Comment by Anyrainel** [comment]
It should be issues of PokemonGo-Bot. This desktop project is just an UI layer. You should check the [bot repository](https://github.com/PokemonGoF/PokemonGo-Bot).

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138

**Comment by itsfolf** [comment]
@tnsbm How is that related with hatching multiple eggs?
