### ISSUE TITLE
 'utf8' codec can't decode byte 0x9c"

### ISSUE THREAD

**Issue by austinxw** [PokemonGoF/PokemonGo-Bot-Desktop#108]
_Issue without proper information won't be answered_
### Actual Behavior

I got " [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c" when I login the game.
### Steps to Reproduce

When I use commands "npm install", I got the following error. 

` Running setup.py develop for pgoapi
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/Users/Ding/Documents/PokemonGo-Bot-Desktop/gofbot/src/pgoapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to pgoapi.egg-info/requires.txt
    writing pgoapi.egg-info/PKG-INFO
    writing top-level names to pgoapi.egg-info/top_level.txt
    writing dependency_links to pgoapi.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'pgoapi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'pgoapi.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/site-packages/pgoapi.egg-link (link to .)
error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/pgoapi.egg-link'

----------------------------------------
```

Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/Users/Ding/Documents/PokemonGo-Bot-Desktop/gofbot/src/pgoapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" develop --no-deps" failed with error code 1 in /Users/Ding/Documents/PokemonGo-Bot-Desktop/gofbot/src/pgoapi/
`

Then I run commands (i.e., sudo -H pip install -r requirements.txt) in folder gofbot, and pgoapi-1.1.6 installed successfully.

Then I run npm start, the error described at the start shows up.
### Information
- OS OS X 10.11
- Git commit ( to get git commit run `git log -1 --format="%H"`)
  npm install

**Comment by tnsbm** [comment]
Check out https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
