### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by kedanf** [PokemonGoF/PokemonGo-Bot-Desktop#109]
Why am I have this import error

![screen shot 2016-08-10 at 2 52 49 pm](https://cloud.githubusercontent.com/assets/20954601/17570584/3071e61c-5f0a-11e6-958f-4a52f9f99007.png)

**Comment by Outpox** [comment]
Please use the search function, other issues like #51 already talks about this error.

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/51#issuecomment-236888095
