### ISSUE TITLE
sorry to ask it seems to be lame but how do i get this running ?

### ISSUE THREAD

**Issue by lightningfuzion2** [PokemonGoF/PokemonGo-Bot-Desktop#11]
I have got the gofbot and web submodule all in place. what do i do after initiating pokecli.py.

**Comment by JVenberg** [comment]
**Try this in the desktop directory:**

```
brew install python node 
pip install virtualenv 
npm install
npm start
```

**Comment by lightningfuzion2** [comment]
does that work in windows too ? i installed node, virtualenv and npm seprately, not sure what brew is exactly. installed all of the above using pip2 install. the npm start dosen't work though.

**Comment by JVenberg** [comment]
Are you in the directory of the repo? Could you also post what the error for npm start is?

**Comment by lightningfuzion2** [comment]
![npm](https://cloud.githubusercontent.com/assets/20586485/17211277/24326fd0-54e6-11e6-9e15-763a821174b4.png)

Yes I am in the repo directory, as you can see in the above image. The rest of the python commands work fine from cmd like pip.

**Comment by JVenberg** [comment]
If npm installed correctly, it be a valid command.
Try [this](https://nodejs.org/en/)

**Comment by lightningfuzion2** [comment]
![npm](https://cloud.githubusercontent.com/assets/20586485/17212174/518395ae-54eb-11e6-901e-d8279c018936.png)

yea was thinking to install the node.js but not from python any way thanks. but now this is the problem X_x.

**Comment by JVenberg** [comment]
Did you run npm install in the directory?

**Comment by weirdohunt** [comment]
hey I get the some  problem as him I did the same thing

**Comment by lightningfuzion2** [comment]
![js error](https://cloud.githubusercontent.com/assets/20586485/17214843/6bf541b4-54f8-11e6-9ef9-a458f49ca2e8.png)

Now this :)

**Comment by JVenberg** [comment]
Can you show me what is in your gofbot file?
It looks like you haven't downloaded gofbot, or you downloaded it yourself and got the wrong version

**Comment by lightningfuzion2** [comment]
![image](https://cloud.githubusercontent.com/assets/20586485/17217630/9e64c6d8-5502-11e6-96c2-ac44ecb5cdeb.png)
yea was my bad didnt take the submodules from the right place. now it works but it is stuck dosent seems to be going ahead.

Also can you suggest me a way so I can keep my local repo in sync with yours using GitHub gui ?

nvm forked the last one out :)

**Comment by lightningfuzion2** [comment]
can not Login with the new Login Page, the page refreshes each time I try to click on login with google after filling the form.

**Comment by JVenberg** [comment]
I should have just fixed the error with the latest commit
5dca2e927d971e58935da9ce3fde16647703edc0

**Comment by lightningfuzion2** [comment]
![image](https://cloud.githubusercontent.com/assets/20586485/17222374/8940e062-5515-11e6-9972-a074a7695a61.png)
Seems to be stuck here for me  nothing going on in the map not the bot.

any way to remove the commits that i made  ?

**Comment by lightningfuzion2** [comment]
![image](https://cloud.githubusercontent.com/assets/20586485/17223670/415e53be-551b-11e6-88a3-17eeaf381924.png)
it says request module missing.

**Comment by JVenberg** [comment]
Did you do: npm install?

**Comment by lightningfuzion2** [comment]
![image](https://cloud.githubusercontent.com/assets/20586485/17224029/cf3af52e-551c-11e6-9576-39625a324305.png)
this is what happens when i do npm install

**Comment by JVenberg** [comment]
Ahhh, okay so right now it only works on mac. You might be able to get around it by going to gofbot directory and running "pip install -r requirements.txt"

**Comment by lightningfuzion2** [comment]
ofcorse coz there is this && sudo command. but I did install the requirements from the gofbot folder.
same result after that as well

**Comment by JVenberg** [comment]
Try

```
pip uninstall requests
pip install requests
```

**Comment by lightningfuzion2** [comment]
done, didn't make any difference, still says requests module missing
guess Should reinstall npm.
any ideas how i do that ?

**Comment by lightningfuzion2** [comment]
not working any ideas  ?

**Comment by lightningfuzion2** [comment]
okay got it https://www.youtube.com/watch?v=Ng5T18HyA-Q is the solution.. 

The above thing did work but just once, when i restarted, I am still getting the missing requests module thing.

**Comment by lightningfuzion2** [comment]
Okay so as it turns out I already had python 2.7 installation, and this is where all the pip installation is going. How do I use the default global python instead of python in pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already have a python 2.7 inatalled, and this is where all the pip installation is going. is there a way for me to change the bot so it would run on global python instead of pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already have a python 2.7 inatalled, and this is where all the pip installation is going. is there a way for me to change the bot so it would run on global python instead of pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already have a python 2.7 inatalled, and this is where all the pip installation is going. is there a way for me to change the bot so it would run on global python instead of pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already have a python 2.7 inatalled, and this is where all the pip installation is going. is there a way for me to change the bot so it would run on global python instead of pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already have a python 2.7 inatalled, and this is where all the pip installation is going. is there a way for me to change the bot so it would run on global python instead of pywin folder?

**Comment by lightningfuzion2** [comment]
Okay so as it turns out i already had a python 2.7 installation, and this is where all the pip installation is going. How do I change the bot so it would run on global python instead from the pywin folder?

**Comment by lightningfuzion2** [comment]
temporarily i have shifted the python to pywin and all works fine, but now it dos't show any pokemon on the map nor does the bot catch any.

**Comment by gungoan** [comment]
I  fix  problem python installed  with  change code  in  main.js:
`pythonCmd = path.join(__dirname, 'pywin', 'python.exe');`
change  to
`pythonCmd = path.join('C:/', 'Python27', 'python.exe');`

It  works for me

**Comment by lightningfuzion2** [comment]
perfect thanks bud!

**Comment by weirdohunt** [comment]
hey guys I got this same issus where do I find gofbot

**Comment by mattrat88** [comment]
wherre do i download gofbot ?

**Comment by mattrat88** [comment]
Uncaught Exception:
Error: ENOENT: no such file or directory, rename '/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/gofbot/config.json.example' -> '/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/gofbot/config.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at renameFiles (/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/main.js:241:12)
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/main.js:263:5
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:138:14
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:106:16
    at Server.onListen (/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:35:5)

**Comment by lightningfuzion2** [comment]
[gofbot](https://github.com/PokemonGoF/PokemonGo-Bot/tree/c7ab5b03cb93b5393bebbc383545a50e8519e57a) << download the zip and copy all its files and folders to the pokemongo-bot-desktop\gofbot folder in the folder

and within that there will be an empty folder "web"

[web](https://github.com/OpenPoGo/OpenPoGoWeb/tree/dc742c598a2636337bd358dae8a558ef02159e8e)<< download the zip and copy all its files and folders to the pokemongo-bot-desktop\gofbot\web folder

**Comment by mattrat88** [comment]
Uncaught Exception:
Error: ENOENT: no such file or directory, rename '/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/gofbot/web/userdata.js.example' -> '/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/gofbot/web/userdata.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at renameFiles (/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/main.js:259:12)
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/main.js:263:5
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:138:14
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:106:16
    at Server.onListen (/Users/mattandadam/Downloads/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:35:5)

**Comment by JVenberg** [comment]
@mattrat88 It looks like you do not have the web repository cloned
You need to download the desktop app with:
`git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop`
