### ISSUE TITLE
pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateTitleStats defined

### ISSUE THREAD

**Issue by jy1989** [PokemonGoF/PokemonGo-Bot-Desktop#114]
_Issue without proper information won't be answered_
### Steps to Reproduce

login with google account
### Information
- OS
  OS X EL Capitan 10.11.3
- Git commit ( to get git commit run `git log -1 --format="%H"`)
  5f9617406ff94ec58e53975d98575612c6ccd953
- App's logs

> abcdefg:PokemonGo-Bot-Desktop chen$ npm start
> 
>  PokemonGoBot@0.0.1-alpha start /Users/chen/Documents/GitHub/PokemonGo-Bot-Desktop
>  electron main.js
> 
> GVA info: Successfully connected to the Intel plugin, offline Gen7 
> Starting Python process...
> Bot path: /Users/chen/Documents/GitHub/PokemonGo-Bot-Desktop/gofbot
> python ./pokecli.py
> Python: [10:51:41]  PokemonGO Bot v1.0 
> 
> Python: [10:51:41]  No config argument specified, checking for /configs/config.json 
> 
> Python: [10:51:41]  Configuration initialized 
> 
> Python: [10:51:41] 
> [10:51:41] Location Found: 22.359,114.127
> 
> Python: [10:51:41] GeoPosition: (22.3589764, 114.1271412, 0)
> [10:51:41] 
> [10:51:41] [x] Parsing cached location...
> 
> Python: [10:51:41] 
> [10:51:41] [x] Last location flag used. Overriding passed in location
> 
> Python: [10:51:41] [x] Last in-game location was set as: (22.36114947159405, 114.12349156713674, 0)
> [10:51:41] 
> [10:51:41] Attempting login to Pokemon Go.
> 
> Python: [10:51:43]  Login to Pokemon Go successful. 
> 
> Python: [10:51:43]  Server seems to be busy or offline - try again - 1/5 
> 
> Python: [10:51:45] 
> 
> Python: [10:51:45]  --- chenjianyi --- 
> 
> Python: [10:51:45]  Level: 17 (Next Level: 12745 XP) (Total: 147255 XP) 
> 
> Python: [10:51:45]  Pokemon Captured: 167 | Pokestops Visited: 1563 
> 
> Python: [10:51:45]  Pokemon Bag: 183/250 
> 
> Python: [10:51:45]  Items: 345/350 
> Python: 
> [10:51:45]  Stardust: 27196 | Pokecoins: 0 
> Python: 
> 
> Python: [10:51:45] 
> Python:  PokeBalls: 70 | GreatBalls: 88 | UltraBalls: 0 
> 
> Python: [10:51:45]  RazzBerries: 85 | BlukBerries: 0 | NanabBerries: 0 
> 
> Python: [10:51:45]  LuckyEgg: 0 | Incubator: 1 | TroyDisk: 3 
> 
> Python: [10:51:45]  Potion: 10 | SuperPotion: 20 | HyperPotion: 30 
> Python: 
> 
> Python: [10:51:45] 
> Python:  Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0 
> [10:51:45]  Revive: 30 | MaxRevive: 0 
> 
> Python: [10:51:45] 
> 
> Python: [10:51:45] 
> 
> Python: [10:51:45] 
> [10:51:45]  Ran for 0:00:05 
> 
> Python: [10:51:45]  Total XP Earned: 0  Average: 0.00/h 
> [10:51:45]  Travelled 0.00km 
> [10:51:45]  Visited 0 stops 
> [10:51:45]  Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before 
> [10:51:45]  Threw 0 pokeballs 
> [10:51:45]  Earned 0 Stardust 
> 
> Python: [10:51:45] 
> [10:51:45]  Highest CP Pokemon:  
> [10:51:45]  Most Perfect Pokemon:  
> 
> Python: Traceback (most recent call last):
>   File "./pokecli.py", line 494, in <module>
>     main()
> 
> Python:   File "./pokecli.py", line 63, in main
>     tree = TreeConfigBuilder(bot, config.raw_tasks).build()
>   File "/Users/chen/Documents/GitHub/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/tree_config_builder.py", line 29, in build
> 
> Python:     worker = self._get_worker_by_name(task_type)
>   File "/Users/chen/Documents/GitHub/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/tree_config_builder.py", line 15, in _get_worker_by_name
> 
> Python:     raise ConfigException('No worker named {} defined'.format(name))
> pokemongo_bot.tree_config_builder.ConfigException: No worker named UpdateTitleStats defined
> 
> Bot exited

**Comment by tnsbm** [comment]
Make a clean install, your gofbot submodule is outdated
