### ISSUE TITLE
Linux install, "Error in python bot" after login

### ISSUE THREAD

**Issue by pyr0ball** [PokemonGoF/PokemonGo-Bot-Desktop#117]
_Issue without proper information won't be answered_
### Expected Behavior

Login, begin botting
### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/8482805/17579437/5534d654-5f4a-11e6-837a-5832068168df.png)
![image](https://cloud.githubusercontent.com/assets/8482805/17579440/6ae99796-5f4a-11e6-9615-1dece6ae1076.png)
### Steps to Reproduce

log in using google, wait 5 seconds
### Information
- OS: Ubuntu 16
- Git commit: 5f9617406ff94ec58e53975d98575612c6ccd953
- App's logs

Starting Python process...
Bot path: /home/tnn/desktop-bot/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Python: 2016-08-10 22:33:35,660 [       cli] [INFO] PokemonGO Bot v1.0

Python: 2016-08-10 22:33:35,661 [       cli] [INFO] No config argument specified, checking for /configs/config.json

Python: 2016-08-10 22:33:35,662 [       cli] [INFO] Configuration initialized

Python: 2016-08-10 22:33:35,662 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-10 22:33:35,662 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics

Python: 2016-08-10 22:33:35,664 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

Python: 2016-08-10 22:33:35,717 [PokemonGoBot] [INFO] [set_start_location] Setting start location.

Python: 2016-08-10 22:33:35,718 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.

Python: 2016-08-10 22:33:35,718 [PokemonGoBot] [INFO] [location_found] Location found: 37.791492, -122.390006 (37.791492, -122.390006, 0.0)

Python: 2016-08-10 22:33:35,718 [PokemonGoBot] [INFO] [position_update] Now at (37.791492, -122.390006, 0)

Python: 2016-08-10 22:33:35,718 [PokemonGoBot] [INFO] [login_started] Login procedure started.

Python: 2016-08-10 22:33:36,576 [PokemonGoBot] [INFO] [login_successful] Login successful.

Python: 2016-08-10 22:33:37,896 [PokemonGoBot] [INFO] 

Python: 2016-08-10 22:33:37,897 [PokemonGoBot] [INFO] --- username ---
2016-08-10 22:33:37,897 [PokemonGoBot] [INFO] Pokemon Bag: 0/250

Python: 2016-08-10 22:33:37,897 [PokemonGoBot] [INFO] Items: 54/350

Python: 2016-08-10 22:33:37,897 [PokemonGoBot] [INFO] Stardust: 0 | Pokecoins: 0

Python: 2016-08-10 22:33:37,897 [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 0 | UltraBalls: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0 | MaxPotion: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0

Python: 2016-08-10 22:33:37,898 [PokemonGoBot] [INFO] 

Python: 2016-08-10 22:33:37,899 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 Encrypt.so directory: /home/tnn/desktop-bot/PokemonGo-Bot-Desktop/gofbot

Python: 2016-08-10 22:33:37,899 [PokemonGoBot] [INFO] 

Python: 2016-08-10 22:33:39,622 [PokemonGoBot] [INFO] [bot_start] Starting bot...

Python: 2016-08-10 22:33:41,315 [       cli] [INFO] 
2016-08-10 22:33:41,316 [       cli] [INFO] Ran for 0:00:06

Python: Traceback (most recent call last):
  File "./pokecli.py", line 522, in <module>

Python:     main()
  File "./pokecli.py", line 138, in main
    report_summary(bot)
  File "./pokecli.py", line 150, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "/home/tnn/desktop-bot/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']
TypeError: 
Python: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

Python: 2016-08-10 22:33:41,323 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/tnn/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/tnn/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/tnn/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/tnn/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

Python: 2016-08-10 22:33:41,324 [sentry.errors.uncaught] [ERROR] [u"TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'", u'  File "pokecli.py", line 522, in <module>', u'  File "pokecli.py", line 138, in main', u'  File "pokecli.py", line 150, in report_summary', u'  File "pokemongo_bot/metrics.py", line 28, in xp_earned']

Bot exited

**Comment by Anyrainel** [comment]
It seems you need support for utf-8.
Have you checked your system setting about encoding? It should be in the "languages" in system settings.
I don't know if this is the reason, just a guess.

**Comment by tnsbm** [comment]
Check out https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138

**Comment by pyr0ball** [comment]
It seems the issue was related to the configuration file being changed by the app. If I launch with a fresh config file it works, however after quitting  and relaunching the error occurs again. 

If I run gofbot and SimpleHTTPServer separately, it works just fine
