### ISSUE TITLE
Workaround for network restrictions?

### ISSUE THREAD

**Issue by ReinyDays** [PokemonGoF/PokemonGo-Bot-Desktop#118]
I'm having a rather niche problem I'm afraid...
### Expected Behavior

Installed and tested bot on work laptop at home, it worked.
### Actual Behavior

I'd like to run it at work, but after login the character doesn't move and no logs are reported.
In the git cmd, it gets stuck on:
'Python: (date+time) [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com'
After a while i get an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range (128) (url: https://app.getsentry.com/api/90254/store/) ...
followed by:
max retries exceede with url /collect ...
which i guess meant that he tried to much and it didn't help?
### Steps to Reproduce

Network restrictions, probably?

Can someone tell me if there is some sort of workaround or am i just screwed? :(
### Information
- OS: windows 7
- Git commit: 584782fa1425e19ff9d94d16728d95781ade3312

**Comment by Outpox** [comment]
Using your work wifi (if available) on your phone, are you able to play the game?  
Most likely a bot issue and not related to the desktop app I'm afraid.

**Comment by ReinyDays** [comment]
Nope, no wifi... 4G reception for tethering is not good enough inside.
should i post this in the main bot issues page?

**Comment by Outpox** [comment]
You may try to disable the health check in your config file (since it seems to get stuck on connection to google analytics) but yeah the guys on the bot repos should be more helpful than me.

**Comment by ReinyDays** [comment]
Hmm... i can't see the option in my config.json, where is it?

**Comment by ReinyDays** [comment]
nvm i'm blind. found it. 
That skips the health check, but i get the same problem at the login. probably not solvable in the program, will have to fix a vpn i suppose.
