### ISSUE TITLE
Question regarding how the Pokemons are detected

### ISSUE THREAD

**Issue by lightningfuzion2** [PokemonGoF/PokemonGo-Bot-Desktop#12]
is it so that the Bot uses "https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop" as a module to exactly find where a Pokemon is ? if it is so then can we choose and target where the character moves (walking) to catch a desired Pokemon in accord with the map above ?

**Comment by lightningfuzion2** [comment]
@JVenberg you think it is Possible for us to use [this repo](https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop) and use another to user find all the pokemons in the map. then catch a particular one by selecting the coordinates for the character to walk towards ?

**Comment by sniok** [comment]
@lightningfuzion2 this is [PoekmonGo-Bot](https://github.com/PokemonGoF/PokemonGo-Bot) related issue
