### ISSUE TITLE
How to activate virtualenv while starting bot in electron main.js?

### ISSUE THREAD

**Issue by Anyrainel** [PokemonGoF/PokemonGo-Bot-Desktop#120]
### Actual Behavior

On my computer an install without virtualenv of PokemonGo-Bot can always run into problem. I'll skip posting the error outputs since I know it is environment issue. Basically, I need virtualenv to run the bot, and I've manually installed everything with virtualenv in `gofbot/penv` (the same location as in provided shell scripts, was trying to be compatible).

I'm not familiar with child_process. I know that in [these lines](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/blob/5f9617406ff94ec58e53975d98575612c6ccd953/main.js#L274-L277), electron starts the bot. Problem is how could I source the virtualenv within this process to get the bot working?
### Information
- OS: Mac OS X
- Git commit 
  5f9617406ff94ec58e53975d98575612c6ccd953

**Comment by Anyrainel** [comment]
Fixed. Just change the first parameter to the python in virtualenv path, like this:

```
  var venvPyPath = path.join(__dirname, 'gofbot', 'penv', 'bin', 'python');
  subpy = require('child_process').spawn(venvPyPath, cmdLine, {
    cwd: path.join(__dirname, 'gofbot'),
    detached: true
  });
```

**Comment by tnsbm** [comment]
Closing
