### ISSUE TITLE
npm install issue (Mac)

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#121]
[npm-debug.log.txt](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/files/413130/npm-debug.log.txt)
**I'm sorry for the form and for my English. I'm German and I'm new to "coding"...**

Everything wen't well but after I used this "npm install" it got fkd up. The whole code is in the file (renamed it to txt because ".log" isn't supported)
### Information
- OS X 10.10.5

**Comment by Anyrainel** [comment]
Hi I have a solution for myself. I can't guarantee but you could feel free to have a try.
Okay, the idea is to use virtualenv for python usage. Two steps:
1. In `package.json`, modify [this line](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/blob/5f9617406ff94ec58e53975d98575612c6ccd953/package.json#L10) to 

```
    "postinstall": "cd ./gofbot/ && virtualenv penv && source penv/bin/activate && pip install -r requirements.txt",
```
1. In `main.js`, modify [this line](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/blob/5f9617406ff94ec58e53975d98575612c6ccd953/main.js#L174) to

```
  var pythonCmd = path.join(__dirname, 'gofbot', 'penv', 'bin', 'python');
```

Hope it can solve your problem. Note that those only work if you followed the install steps, especially don't forget `pip install virtualenv`.

P.S: I wish I could submit a PR, however, virtualenv works differently in Windows. I don't know how to make the postinstall differ based on system.

Edit: Please leave comment if it works :)

**Comment by MrAppleMania** [comment]
I created a new user and everything works fine there. I forgot to say, that when I did `pip install virtualenv` it said something like "it won't be cached and that I'm not the owner of the "folder". But I'm so thankful that someone (you :)) replied to my question and anyways thanks!
