### ISSUE TITLE
Error after log in.

### ISSUE THREAD

**Issue by DhrFavor** [PokemonGoF/PokemonGo-Bot-Desktop#123]
![pokemon](https://cloud.githubusercontent.com/assets/20970227/17588700/efc9e930-5fd0-11e6-91df-abcb3d91bda3.PNG)
I get this error when i run the bot, i am not great at this. And i dont really know what to do to fix it?

Can someone explain it carefully please?

**Comment by tnsbm** [comment]
enctrypt.dll is not found! Please download it and select it when logging in

**Comment by DhrFavor** [comment]
Where can i download it?

**Comment by DhrFavor** [comment]
Can somebody help me?

**Comment by tnsbm** [comment]
Check out https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
