### ISSUE TITLE
Build it encrypt.so

### ISSUE THREAD

**Issue by Thehackerzii** [PokemonGoF/PokemonGo-Bot-Desktop#126]
![5](https://cloud.githubusercontent.com/assets/20965536/17589625/090fc1ec-6000-11e6-8b54-97d6d2e1f299.jpg)

Create a new separate folder somwhere
Run wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make 

in ?  Help me !!!!

**Comment by Anyrainel** [comment]
You should run `wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make` in a terminal. In case of you are Windows user, you might want to manually download and unzip, then run make in `pgoencrypt/src/`

**Comment by Thehackerzii** [comment]
![image](https://cloud.githubusercontent.com/assets/20965536/17590487/2510f20e-6004-11e6-8154-5f13c9d5d9b4.png)
Select file ?

**Comment by Anyrainel** [comment]
For windows, you need encrypt.dll. Go to the [slack channel](https://pokemongo-bot.herokuapp.com/) and ask them.

**Comment by Thehackerzii** [comment]
I Have encrypt.dll Work it
