### ISSUE TITLE
Cannot find module 'jquery', map frozen and always showing 'Loading...' on account info

### ISSUE THREAD

**Issue by cezarsmpio** [PokemonGoF/PokemonGo-Bot-Desktop#127]
### Expected Behavior

Account info and map updated must be updated.

<img width="307" alt="captura de tela 2016-08-11 as 11 37 34" src="https://cloud.githubusercontent.com/assets/954889/17592290/19fb4cda-5fb8-11e6-95c6-2e8cd3195168.png">
![captura de tela 2016-08-11 as 11 37 32](https://cloud.githubusercontent.com/assets/954889/17592439/b27ce9b4-5fb8-11e6-820e-e896af071915.png)
<img width="568" alt="captura de tela 2016-08-11 as 11 37 45" src="https://cloud.githubusercontent.com/assets/954889/17592440/b29b6d26-5fb8-11e6-8155-aa9d3f525036.png">
### Actual Behavior

Account info is always showing 'Loading...'
Map is frozen.
### Steps to Reproduce

Install normally, npm start and log in.  
### Information
- macOS
- PikaBot 0.0.1-alpha

**Comment by tnsbm** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/pull/135
