### ISSUE TITLE
Trainer information and map data stuck on "Loading..."

### ISSUE THREAD

**Issue by Kujawadl** [PokemonGoF/PokemonGo-Bot-Desktop#128]
### Expected Behavior
- Trainer information should be available.
- Map should follow trainer.
- Pokémon and Pokéstops should be displayed on the map.
#### What works:
- Bot logs in and operates as expected, logs load in the log window, trainer status is updated properly in lower right corner. Settings menu is clickable, but obviously does nothing (no map info = no settings to change).
#### What doesn't:
- The trainer menu displays "Loading..." (clicking does nothing).
- Map stays zoomed out, not following the trainer. Zooming into my location shows only google maps, no additional information or markers are placed on the map.
### Information
- **OS:** Mac OS X 10.11.6
- **Git commit:** 98226a9e107c0ec626ab3a4ca674d30fefa2d755
- **App's logs:** _(On my way to work... Will attach logs later this afternoon)_

![screen shot 2016-08-11 at 9 42 09 am](https://cloud.githubusercontent.com/assets/14938364/17592505/31567ec8-5fa8-11e6-80c8-e2270db0a7be.png)

**Comment by MrAppleMania** [comment]
Same issue here. Hope that someone finds a fix.

**Comment by tnsbm** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/pull/135
