### ISSUE TITLE
electron main.js // not exist

### ISSUE THREAD

**Issue by rocket13011** [PokemonGoF/PokemonGo-Bot-Desktop#131]
git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop
pip install virtualenv
cd PokemonGo-Bot-Desktop
npm install
npm start
### Information
- MAC OSX
- Git commit c76537b0fc40f3688770e1e01c1a1f39c66abd14
- App's logs

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart PokemonGoBot@0.0.1-alpha
6 info start PokemonGoBot@0.0.1-alpha
7 verbose unsafe-perm in lifecycle true
8 info PokemonGoBot@0.0.1-alpha Failed to exec start script
9 verbose stack Error: PokemonGoBot@0.0.1-alpha start: `electron main.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid PokemonGoBot@0.0.1-alpha
11 verbose cwd /Users/xxxx/Desktop/pokemon-Go/PokemonGo-Bot-Desktop
12 error Darwin 15.5.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error PokemonGoBot@0.0.1-alpha start: `electron main.js`
17 error Exit status 1
18 error Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
18 error This is most likely a problem with the PokemonGoBot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls PokemonGoBot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ts1987** [comment]
having the same issue after updated. any fix?

**Comment by BoGnY** [comment]
have same problem.. on windows:

> $ npm start
> 
> > PokemonGoBot@0.0.1-alpha start C:\Luca\PokemonGO\bot_desktop
> > electron main.js
> 
> "electron" non ▒ riconosciuto come comando interno o esterno,
>  un programma eseguibile o un file batch.
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron main.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs PokemonGoBot
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls PokemonGoBot
> npm ERR! There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Luca\PokemonGO\bot_desktop\npm-debug.log

**Comment by Outpox** [comment]
Yeah you can re-pull the repo now.

**Comment by Outpox** [comment]
Also @BoGnY just read the error log. It's written `Local package.json exists, but node_modules missing, did you mean to install` so you just forgot to `npm install`

**Comment by ts1987** [comment]
just did a re-pull. working right now. thanks.

**Comment by BoGnY** [comment]
yes sorry, my fault!! :)

**Comment by ts1987** [comment]
hmm. it seems like the same problem exists again.

**Comment by Outpox** [comment]
Yeah sorry we're doing some heavy changes right now, I suggest you stick to the [releases files](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases) for now.

**Comment by ts1987** [comment]
alright. thanks.

**Comment by christig** [comment]
I tried the reinstall which also failed. Outpox's solution to stick to the [release files](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases) worked for me.
