### ISSUE TITLE
Encrypt.dll

### ISSUE THREAD

**Issue by ShadowZeroX** [PokemonGoF/PokemonGo-Bot-Desktop#137]
I'm new on Gifthub, how i can find or download it?

**Comment by MrAppleMania** [comment]
Create a new folder on your desktop and name it like you want (let's say TestFolder).

Then go in your terminal and enter the following code:
`cd desktop/TestFolder`.

Then enter this code:
`wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make`

Then copy libencrypt.so to the gofbot folder and rename to encrypt.so

Edit: If it doesn't work, then you didn't install the "wget" function.

**Comment by Outpox** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt

**Comment by tnsbm** [comment]
Check out #138
