### ISSUE TITLE
How to set starting location

### ISSUE THREAD

**Issue by jurjen2000** [PokemonGoF/PokemonGo-Bot-Desktop#14]
Probably a stupid question but every time I run pokecli.py the starting location is 0, 0 thus somewhere in the middle of the ocean from where it tries to walk towards the location I set in the config file. Is there any place where I can set the starting location such that it is close to the location in the config file?

**Comment by lightningfuzion2** [comment]
Try changing the location in config.json "location":"XX.ZZZZZZ,YY.ZZZZZZ" you will find it in gofbot.
that may do the job.

**Comment by JVenberg** [comment]
You don't want to run pokecli.py. You want to run npm install which will automatically run pokecli.py. Then you will be able to edit the location from there
