### ISSUE TITLE
I Have the error "Unable to find Electron app at ..." after run npm start, any idea to solve this problem?

### ISSUE THREAD

**Issue by kennedyrs** [PokemonGoF/PokemonGo-Bot-Desktop#141]
ASUS+kennedy@asus MINGW64 /d/projetos/www/pokemon/PokemonGo-Bot-Desktop (development)
$ npm start

> PokemonGoBot@0.0.1-alpha start D:\projetos\www\pokemon\PokemonGo-Bot-Desktop
> electron main.js

**Comment by tnsbm** [comment]
> THE BOT IS CURRENTLY UNDERGOING A MAJOR BUILD SYSTEM REVAMP PLEASE BE PATIENT
