### ISSUE TITLE
Failed to import Materialize

### ISSUE THREAD

**Issue by filipac** [PokemonGoF/PokemonGo-Bot-Desktop#143]
### Expected Behavior

npm start should start the program succesfully
### Actual Behavior

npm starts but the style is broken. If you look into the therminal you get this error:

```
[00:00:05] Starting 'build:src'...
Error in plugin 'sass'
Message:
    src/styles/main.scss
Error: File to import not found or unreadable: Materialize
       Parent style sheet: /home/filip/PokemonGo-Bot-Desktop/src/styles/main.scss
        on line 1 of src/styles/main.scss
>> @import "Materialize";
   ^

[00:00:05] Finished 'build:src' after 682 ms
```
### Steps to Reproduce

Checkout the latest repository version
### Information
- OS Ubuntu x64
- Git commit f19fd4c155d720e3f51a2be6a82d0a0fa2f7a8c0

**Comment by filipac** [comment]
PS: It used to work today, but i decided to `git pull` to see the latest changes.

**Comment by richardgetz** [comment]
Same issue on macOS Sierra, also did a git pull.

**Comment by ProjectBarks** [comment]
Pull now? It works on my machine. Make sure you do `npm install` before doing `npm start`

**Comment by filipac** [comment]
Now i don't get the error (after a fresh clone and `npm install`) but the app looks like crap.
![screenshot from 2016-08-12 08-39-57](https://cloud.githubusercontent.com/assets/271155/17613689/94325880-6068-11e6-910f-b3bc8abe3467.png)

**Comment by Outpox** [comment]
I can confirm the issue, and I fixed it. Will share a PR soon.
