### ISSUE TITLE
unable to pull submodule gofbot 

### ISSUE THREAD

**Issue by ts1987** [PokemonGoF/PokemonGo-Bot-Desktop#146]
_Issue without proper information won't be answered_
### Information
- OS MacOSX 
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

ubmodule 'build/gofbot' (git@github.com:PokemonGoF/PokemonGo-Bot.git) registered for path 'build/gofbot'
Cloning into '/Users/xxx/Documents/PokemonGo-Bot-Desktop/build/gofbot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PokemonGoF/PokemonGo-Bot.git' into submodule path '/Users/xxx/Documents/PokemonGo-Bot-Desktop/build/gofbot' failed

**Comment by taco1124** [comment]
how do u fix this problem bro 👍

**Comment by ts1987** [comment]
u would need to generate a ssh key and add it in your github account.
