### ISSUE TITLE
unable to complete installation

### ISSUE THREAD

**Issue by ts1987** [PokemonGoF/PokemonGo-Bot-Desktop#147]
_Issue without proper information won't be answered_
### Expected Behaviour

installation to be completed
### Actual Behaviour

stopped at submodule gofbot pull.
### Information
- OS Mac OSX 
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

ubmodule 'build/gofbot' (git@github.com:PokemonGoF/PokemonGo-Bot.git) registered for path 'build/gofbot'
Cloning into '/Users/xxx/PokemonGo-Bot-Desktop/build/gofbot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PokemonGoF/PokemonGo-Bot.git' into submodule path '/Users/xxx/PokemonGo-Bot-Desktop/build/gofbot' failed

**Comment by vincentcsm** [comment]
same here
seems problem occur after gofbot relocated to build folder

**Comment by filipac** [comment]
create a public key and add it to github account

**Comment by ts1987** [comment]
thanks bro. it's working now.
