### ISSUE TITLE
Gulp is broken

### ISSUE THREAD

**Issue by dutchiexl** [PokemonGoF/PokemonGo-Bot-Desktop#148]
_Issue without proper information won't be answered_
### Expected Behavior

When doing a npm install, the gulp build fails
### Actual Behavior

Gulp gets stuck on parsing different parts of the file.
- The first error is on th ``` character: const PACKAGES = `${BUILD_DIR}/packages`; when I replace these with normal ones it gets trough but then gets stuck on `gulp.task('python:install', callback => {` `SyntaxError: Unexpected token =>`

As I have never seen this kind of syntax in gulp and cannot find anything on google about it, I don't know how to fix this
### Steps to Reproduce

run npm install or npm start or gulp build
### Information
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by ts1987** [comment]
deleted.

**Comment by dutchiexl** [comment]
it seems you have another issue. Your gulp is running, but python fails. So this is not a gulp error

**Comment by ts1987** [comment]
okay. will open another issue. thanks.

**Comment by Outpox** [comment]
Node and npm version please :)

**Comment by dutchiexl** [comment]
Sorry clearing the npm cache did the trick,
