### ISSUE TITLE
invalide syntax error

### ISSUE THREAD

**Issue by rykermorgan** [PokemonGoF/PokemonGo-Bot-Desktop#15]
Not exactly sure what is happening here.

![screen shot 2016-07-28 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/15041304/17227529/fd0bfc74-54cb-11e6-8125-37b7926ab726.png)

**Comment by sniok** [comment]
Make a clean install of latest version. Don't forget to do `npm install`

**Comment by rykermorgan** [comment]
I did that multiple times and kept getting the same result. I'm not going to worry about it since there is a packaged alpha up now. But I really won't worry about it until the api is figured out again.

Thx

**Comment by sniok** [comment]
As you can see, the error appears in serveit.py file. We don't have it anymore. And you were missing module that means something when wrong when you did `npm install`
