### ISSUE TITLE
it's encrypt.dll and i've gone through #138

### ISSUE THREAD

**Issue by wvjgsuhp** [PokemonGoF/PokemonGo-Bot-Desktop#154]
### Expected Behavior

After choosing encrypt **or** rename the file to "encrypt.so" and put it in gofbot folder, the app should work fine.
### Actual Behavior

The app is still asking for encrypt.dll
![ff](https://cloud.githubusercontent.com/assets/20987347/17617677/98edb51c-60a5-11e6-9188-531b6cc505d7.jpg)
### Information
- Windows 8.1 x64
- App's logs
  2016-08-16 15:57:25,551 [PokemonGoBot] [ERROR] encrypt.dll is not found! Please place it in the bots root directory or set libencrypt_location in config.

**Comment by Outpox** [comment]
You're not supposed to rename the file to `encrypt.so` on Windows, it must stay `encrypt.dll`.

**Comment by wvjgsuhp** [comment]
well.. it goes like this then
![ff](https://cloud.githubusercontent.com/assets/20987347/17619853/5582e286-60b2-11e6-8510-392caba6e88e.jpg)
