### ISSUE TITLE
phyton bot error after login

### ISSUE THREAD

**Issue by wvjgsuhp** [PokemonGoF/PokemonGo-Bot-Desktop#157]
### Expected Behavior

botting after login
### Actual Behavior

![ff](https://cloud.githubusercontent.com/assets/20987347/17620747/adb514d2-60b8-11e6-9d1e-716a6b27463e.jpg)
### Information
- windows 8.1 x64

**Comment by RaymondCM** [comment]
I also get the same message after doing full re-install of the latest commit. 

![image](https://cloud.githubusercontent.com/assets/16948324/17620903/9880b566-6087-11e6-893f-614214517d46.png)

## Information

windows 10 x64

**Comment by RaymondCM** [comment]
I fixed  it by setting health_record to false in gofbot config.

**Comment by MrAppleMania** [comment]
RaymondKirk it stills crashes... :( but the message doesn't appear anymore

**Comment by ProjectBarks** [comment]
This is a consequence of an old bot. We will be releasing a new version where this problem does not occur. Sorry for the inconvenience!

**Comment by wvjgsuhp** [comment]
so, i have to patiently wait.. right?

**Comment by Outpox** [comment]
Yep.

**Comment by wvjgsuhp** [comment]
alright
