### ISSUE TITLE
Problem with Encrypt File

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#159]
_Issue without proper information won't be answered_
### Expected Behavior

Let me choose the Encrypt File
### Actual Behavior

Button is named "button" and when I choose it it doesn't mark it as "selected"
### Steps to Reproduce

Opened the bot, entered all the information, chosen the file and it still said "button"
### Information
- OS X 10.10.5
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by Outpox** [comment]
Yep it's an issue related to the recent rework, it will be fixed soon.
Thanks.

**Comment by MrAppleMania** [comment]
Oh ok, glad to hear that :) and you guys are doing a great job! 👍
