### ISSUE TITLE
main.html:138 Uncaught TypeError

### ISSUE THREAD

**Issue by remco1271** [PokemonGoF/PokemonGo-Bot-Desktop#16]
The bot is showing the map but i can't see the Pokemon's and my items.
I have created a API key for Google Maps.
The error list from the console:
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
main.html:86 Error getting location, trying second provider PositionError
main.html:88 Found location [52.3824,4.8995] by ipinfo.io
main.html:134 about:blank
main.html:138 Loaded pokemon data..
main.html:138 Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
4main.html:138 [object XMLHttpRequest]
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'inventory_item_data' of undefined
main.html:138 Uncaught TypeError: Cannot read property 'length' of undefined
![pokemon](https://cloud.githubusercontent.com/assets/6353023/17227398/77bfc968-550e-11e6-8e46-da29a2bc5cdb.png)

**Comment by cdiaz** [comment]
@remco1271 you can solve this?.
I have the same problem in Linux

**Comment by 13werwolf13** [comment]
I also encountered this

**Comment by JVenberg** [comment]
This is an error with the bot not starting. I'm am currently trying to fix it. It is trying to read location values that the bot has not written

**Comment by sniok** [comment]
Already fixed
