### ISSUE TITLE
Encrypt problem w/ encrypt64bit.dll

### ISSUE THREAD

**Issue by nathan30** [PokemonGoF/PokemonGo-Bot-Desktop#162]
_Issue without proper information won't be answered_
### Expected Behavior

Application started
### Actual Behavior

Error in python bot
### Information

I download the Pikabot with this link : https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases/download/v0.0.2-alpha/PikaBot-0.2-alpha-win.zip

I download the encrypt64bit.dll and put it in the same folder of PikaBot.exe. I select it into the Login window and here is the error I've got : http://puu.sh/qz2Nj/02b2a942ad.png

I'm under Windows 10 

Thanks in advance for the help

**Comment by Outpox** [comment]
Rename encrypt64bit.dll to encrypt.dll

**Comment by nathan30** [comment]
This is what I did. Here is my root folder : http://puu.sh/qz3u9/e8b7611fd0.png 
I try without select it into the "encrypt file" section in the home, and with select it. Same problem each time

**Comment by layerlre** [comment]
I have the same problem.

**Comment by renatogg** [comment]
You need to put it in **_resources -> app -> gofbot_** directory.

**Comment by layerlre** [comment]
@Renato-Garcia I put encrypt.dll inresources -> app -> gofbot directory.
New error : https://postimg.org/image/le0mq37yt/

**Comment by RoyLeeKB** [comment]
I have the same issue even after putting encrypt.dll in resources>app>gofbot

**Comment by potato16** [comment]
same here

**Comment by KingMatt123** [comment]
Same here, please figure what on earth is going on

**Comment by potato16** [comment]
I just changed resources -> app -> gofbot/encrypt.2 to encrypt.dll and it's work for me.

**Comment by nathan30** [comment]
@layerlre it's because you choose the 64bit version of encrypt.dll instead of 32bit. Or inversely

**Comment by layerlre** [comment]
@nathan30 thanks bro, it's working now.

**Comment by KingMatt123** [comment]
thank you! I'm on 64 bit and only the 32 bit version worked thanks!

**Comment by mojo2k** [comment]
Thanks Potato16 it is worked.

**Comment by LUCKASSs** [comment]
Yeah just put the 32bit and that work for me ! Amazing.
