### ISSUE TITLE
More Option

### ISSUE THREAD

**Issue by arguiot** [PokemonGoF/PokemonGo-Bot-Desktop#163]
_Issue without proper information won't be answered_
### Expected Behavior

I would like more option, more button like a "return home" button or more settings.
### Actual Behavior

there is not a lot of button/settings.
### Information
- Mac OS X El Capitan

**Comment by EvanTheTerrible** [comment]
If you want to edit the bot's configuration, you can right click on the app, click view package contents, then navigate to Contents, Resources, App, gofbot, configs and then edit the config.json file with textedit. Make sure that any quotation marks you work around don't change to smart quotes. Looks like that's your only option at this time.
