### ISSUE TITLE
Not able to git clone --recursive

### ISSUE THREAD

**Issue by titogarrido** [PokemonGoF/PokemonGo-Bot-Desktop#167]
_Issue without proper information won't be answered_
### Expected Behavior

Able to clone successfuly
### Actual Behavior

git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop
Cloning into 'PokemonGo-Bot-Desktop'...
remote: Counting objects: 2357, done.
remote: Total 2357 (delta 0), reused 0 (delta 0), pack-reused 2357
Receiving objects: 100% (2357/2357), 27.34 MiB | 688.00 KiB/s, done.
Resolving deltas: 100% (618/618), done.
Checking connectivity... done.
Checking out files: 100% (1554/1554), done.
Submodule 'build/gofbot' (git@github.com:PokemonGoF/PokemonGo-Bot.git) registered for path 'build/gofbot'
Cloning into 'build/gofbot'...
**Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:PokemonGoF/PokemonGo-Bot.git' into submodule path 'build/gofbot' failed**
### Steps to Reproduce

Execute git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop
### Information
- OS: Ubuntu 14.04.05 LTS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by taco1124** [comment]
try to add ssh key to your git account 👍
