### ISSUE TITLE
npm install failed - let can only be used in strict mode

### ISSUE THREAD

**Issue by yutelin** [PokemonGoF/PokemonGo-Bot-Desktop#168]
_Issue without proper information won't be answered_
### Expected Behavior

npm install passed
### Actual Behavior

npm install failed
### Steps to Reproduce

run npm install
### Information
- OS OSX
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs
### Fix

Add "'use strict';" in gulpfile.js

**Comment by ProjectBarks** [comment]
This has been fixed in a recent commit  0b5becf7038e16430eb04b1753c5b5e38859ac35
