### ISSUE TITLE
npm install failed - DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

### ISSUE THREAD

**Issue by yutelin** [PokemonGoF/PokemonGo-Bot-Desktop#169]
_Issue without proper information won't be answered_
### Expected Behavior

npm install passed
### Actual Behavior

npm install failed
### Steps to Reproduce

run npm inatall
### Information
- OS OSX
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs
### Fix

edit ~/.pydistutils.cfg 
add following line

```
[install]
prefix=
```

**Comment by chuanxd** [comment]
see commit
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/commit/6197af18cefef33d58a6743fee25598e49744e51
