### ISSUE TITLE
Bot works but GUI doesn't

### ISSUE THREAD

**Issue by lucaskunzler** [PokemonGoF/PokemonGo-Bot-Desktop#171]
After I log in using the GUI it just stays frozen and unresponsive. The only thing I can do is use the top bar menu.
Checking the logs I can see the bot works fine and throw no errors.

![pikabot](https://cloud.githubusercontent.com/assets/10011802/17641882/2124907e-6108-11e6-93c6-72c81d65c2f5.png)
- Windows 10

**Comment by lucaskunzler** [comment]
Gonna try a bit more, I'll reopen if needed or update here if I can solve myself.

**Comment by flawnn** [comment]
have same Problem ;(

**Comment by flawnn** [comment]
do you have a solution
