### ISSUE TITLE
Error when "git clone --recursive..."

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#172]
NAME:~ NAME$ `git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop`

> Cloning into 'PokemonGo-Bot-Desktop'...
> remote: Counting objects: 2363, done.
> remote: Compressing objects: 100% (6/6), done.
> remote: Total 2363 (delta 2), reused 0 (delta 0), pack-reused 2357
> Receiving objects: 100% (2363/2363), 27.34 MiB | 186.00 KiB/s, done.
> Resolving deltas: 100% (620/620), done.
> Checking connectivity... done.
> Submodule 'build/gofbot' (git@github.com:PokemonGoF/PokemonGo-Bot.git) registered for path 'build/gofbot'
> Cloning into 'build/gofbot'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:PokemonGoF/PokemonGo-Bot.git' into submodule path 'build/gofbot' failed

I don't know what I did wrong :( just entered the first command in terminal and pressed enter.

OS X Yosemite 10.10.5

**Comment by chuanxd** [comment]
#167 
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
