### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#173]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

OS X Yosemite 10.10.5

**Comment by Outpox** [comment]
Which commit are you currentrly on?
Also you may try to upgrade your Node.

**Comment by MrAppleMania** [comment]
It's working now, thanks. :)
