### ISSUE TITLE
npm ERR! weird error 127

### ISSUE THREAD

**Issue by dralnux** [PokemonGoF/PokemonGo-Bot-Desktop#174]
When try running the program, I encounter this error:

sh: 1: gulp: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by Outpox** [comment]
Follow [the instructions](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop#install) or #138.
`sh: 1: gulp: not found`

**Comment by dralnux** [comment]
Thanks Outpost.
