### ISSUE TITLE
missing encrypt.dll

### ISSUE THREAD

**Issue by dvdknaap** [PokemonGoF/PokemonGo-Bot-Desktop#176]
Just downloaded the latest release but when i logged in i get the following error:
[Window Title]
Whoops

[Main Instruction]
Error in python bot

[Content]
2016-08-13 14:58:04,315 [PokemonGoBot] [ERROR] encrypt.dll is not found! Please place it in the bots root directory or set libencrypt_location in config.

[Yes I read carefully error message]

De file is not in the downloaded zip file.

**Comment by tnsbm** [comment]
#138

**Comment by DutchProgrammer** [comment]
That fix doesnt help, i keep getting the same error.
