### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by wvjgsuhp** [PokemonGoF/PokemonGo-Bot-Desktop#180]
_Issue without proper information won't be answered_
### Expected Behavior

Logging in and botting
### Actual Behavior

The app went back to login screen
### Information
- Windows 8.1 x64
- App's logs
  Starting Python process...
  Bot path: C:\Users\wvjgsuhp\PokemonGo-Bot-Desktop\build\gofbot
  python ./pokecli.py
  [2016-08-13T18:01:07.043Z] [electron-connect] [server] client (window_id: 1) closed.
  Python: Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "packages\pgoapi__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "packages\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "packages\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "packages\pgoapi\utilities.py", line 30, in <module>
    import xxhash
  ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by Outpox** [comment]
Did you selected the `encrypt.dll` with the button on the login screen?

**Comment by wvjgsuhp** [comment]
i place the file in gofbot folder

**Comment by Outpox** [comment]
`pip install -r requirements.txt`
#138
