### ISSUE TITLE
When running "npm run"

### ISSUE THREAD

**Issue by BurntDiamondz** [PokemonGoF/PokemonGo-Bot-Desktop#181]
I am completely new to this but I got this trying to execute "npm run gulp build" and run it says this:

C:\Users\Kieran\PokemonGo-Bot-Desktop>npm run gulp build
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "run" "gulp" "build"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! missing script: gulp
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kieran\PokemonGo-Bot-Desktop\npm-debug.log

**Comment by Outpox** [comment]
`npm run` and `gulp build` are two differen commands

**Comment by BurntDiamondz** [comment]
gulp build isnt even a command

**Comment by BurntDiamondz** [comment]
I just wanna know how to set this up without errors

**Comment by Outpox** [comment]
Then read the readme file, everything is explained.
You might also want to download a build and then just click and run.
Also check this if you haven't already #138
