### ISSUE TITLE
Where Config number of item and pokemon to evolve?

### ISSUE THREAD

**Issue by jacoborequena** [PokemonGoF/PokemonGo-Bot-Desktop#182]
I Used Windows 10... where config number of item to drop and evolucionable pokemon?

_Issue without proper information won't be answered_
### Information
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by KDA809** [comment]
i cant find this OSX version

**Comment by KDA809** [comment]
https://github.com/iiCe89/PokemonGo-bot-config pre made config.json code you can copy an paste into own
