### ISSUE TITLE
Map starts, but nothing else happens

### ISSUE THREAD

**Issue by JohnnyOmm** [PokemonGoF/PokemonGo-Bot-Desktop#19]
picture [here](http://prntscr.com/byvun9)

**Comment by jujucollins** [comment]
Mine starts as well, shows pokestops and gyms, character also moves but isn't doing anything. Not sure if i'm not doing something.
<img width="1273" alt="screen shot 2016-07-28 at 9 48 49 pm" src="https://cloud.githubusercontent.com/assets/19849944/17238089/8cf232d6-550d-11e6-9bea-3ed331ec3101.png">

**Comment by lightningfuzion2** [comment]
okay so it seems there is a problem with the way the gofbot\config.json is being written after the login.

The Mode apparently gets set to "on" where it actually should be "all" or "poke" or "farm" for the bot to work correctly.
have't got the solution to it yet though.

**Comment by Rlewisrlou666** [comment]
Is there a way to specify the config file to load on start up?

**Comment by mattrat88** [comment]
when i load it up i get a ced john erro ? and its not in the gotbot folder so ity was never created ?

**Comment by JVenberg** [comment]
This means that the bot failed to run. You will half to post the console output  to diagnose the issue
