### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by lapras08** [PokemonGoF/PokemonGo-Bot-Desktop#193]
Please help me. I get this error.

> xxx-MacBook-Pro:bot xxx$ ./run.sh
> Traceback (most recent call last):
>   File "pokecli.py", line 39, in <module>
>     from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
> ImportError: No module named pgoapi.exceptions
> Sun Aug 14 22:00:13 MYT 2016 Pokebot  Stopped.
> Press any button or wait 20 seconds to continue.

after trying pip install -r requirements.txt i get this:

> xxx-MacBook-Pro:bot xxx$ pip install -r requirements.txt
> Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
>   Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
> Collecting networkx==1.11 (from -r requirements.txt (line 2))
>   Using cached networkx-1.11-py2.py3-none-any.whl
> Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
>   Cloning https://github.com/keyphact/pgoapi.git (to a2755eb42dfe49e359798d2f4defefc97fb8163d) to ./src/pgoapi
> Command "git clone -q https://github.com/keyphact/pgoapi.git /Users/xxx/Desktop/bot/src/pgoapi" failed with error code -11 in None
> xxx-MacBook-Pro:bot xxx$ 

After get this error python window pop ups.

> Process:         Python [65985]
> Path:            /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> Identifier:      Python
> Version:         ??? (???)
> Code Type:       X86-64 (Native)
> Parent Process:  Python [65248]
> 
> Date/Time:       2016-08-14 22:05:09.155 +0800
> OS Version:      Mac OS X 10.7.5 (11G63)
> Report Version:  9
> 
> Interval Since Last Report:          453136 sec
> Crashes Since Last Report:           18
> Per-App Crashes Since Last Report:   7
> Anonymous UUID:  
> Crashed Thread:  Unknown
> 
> Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028
> 
> Backtrace not available
> 
> Unknown thread crashed with X86 Thread State (64-bit):
>   rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
>   rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
>    r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
>   r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
>   rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
> Logical CPU: 6
> 
> Binary images description not available
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 1208
>     thread_create: 0
>     thread_set_state: 0

**Comment by ProjectBarks** [comment]
Please download the releases on our home page.

**Comment by flawnn** [comment]
make in gofbot: source bin/activate
