### ISSUE TITLE
Can not log in to Google account with 2FA enabled

### ISSUE THREAD

**Issue by rojepp** [PokemonGoF/PokemonGo-Bot-Desktop#194]
### Expected Behavior

Be able to login with a Google account that has two factor authentication enabled
### Actual Behavior

> Error in python bot: 
> 2016-08-14 16:15:48,475 [pgoapi.pgoapi] [ERROR] Login process failed: Invalid Google Username/password
### Steps to Reproduce

Just login with a google account that has "FA enabled
### Information
- OSX
- Latest prebuilt

**Comment by pawelorzech** [comment]
Just use app specific password, you can generate them on your google profile page.

**Comment by rojepp** [comment]
Thanks, I did not know about this. Closing..
