### ISSUE TITLE
No map

### ISSUE THREAD

**Issue by Laurin100** [PokemonGoF/PokemonGo-Bot-Desktop#197]
When I am using the pikadesktop bot on os x then there is no map he only saying me:
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by giancarlosisasi** [comment]
same here

**Comment by layerlre** [comment]
same here

**Comment by ProjectBarks** [comment]
You forgot your API key for google maps. It should be on the login screen.

**Comment by Laurin100** [comment]
I typed in a google maps browser key.
