### ISSUE TITLE
CATCH FILTER NOT WORKING!

### ISSUE THREAD

**Issue by legend1903** [PokemonGoF/PokemonGo-Bot-Desktop#198]
### Expected Behavior

CATCH FİLTER
### Actual Behavior

CATCH FİLTER NOT WORKING
### Information

I created the code to dont catch some Pokemon. I do not want to catch the low cp. But code not working. And "keep_best_cp": 2, code not working. As I said 2, but catching pokemon 7,8,9...  

Please help me. Thanks..

EXAMPLE CATCH FILTER CODE: 
    "catch": {
        "any": {
            "catch_above_cp": 700,
            "logic": "or"
        },
        "Zubat": {
            "logic": "or",
            "catch_above_cp": 700
        },
        "Pidgey": {
            "logic": "or",
            "catch_above_cp": 700
        },
        "Caterpie": {
            "logic": "or",
            "catch_above_cp": 500
        },
        "Ekans": {
            "logic": "or",
            "catch_above_cp": 700
        },
        "Growlithe": {
            "logic": "or",
            "catch_above_cp": 700
        }
    },

**Comment by vincentcsm** [comment]
keep_best_cp": 2 should use in release function such like:
  "release": {
        "any": {
            "keep_best_iv": 2
        },

**Comment by legend1903** [comment]
I've tried. it does not work!

**Comment by myworkpool** [comment]
"catch": {
  "any": {
      "catch_above_cp": 700,
  }
},

remove that OR condition because you didn't use it

**Comment by legend1903** [comment]
I tried it:

"catch": {
"any": {
"catch_above_cp": 700,
}
},

**When I click the login with GOOGLE button, I get the error message:**

**"a javascript error occurred in the main process"**

**Comment by ProjectBarks** [comment]
@legend1903 Removed the comma after `"catch_above_cp": 700,<-- This comma`. In JSON you cannot have a comma at the end of a list or a map.

So if you had multiple it should look like this

```
"catch": {
    "any": {
        "catch_above_cp": 700
    }, <--- Notice the comma
    "Magikarp": {
        "catch_above_cp": 50 <--- One item so no comma
    } <--- Notice no comma
},
```
