### ISSUE TITLE
do i have to start the gobot ?

### ISSUE THREAD

**Issue by weirdohunt** [PokemonGoF/PokemonGo-Bot-Desktop#20]
so I installed all the parts, npm starts gets though login and sits on a world map.
question, how do I start gobot, I have set up the .config. is it just 
pokecli.py

![test](https://cloud.githubusercontent.com/assets/20646791/17243731/a382e34c-55c1-11e6-8ab4-3ee9eda17539.jpg)

![test2](https://cloud.githubusercontent.com/assets/20646791/17243926/8779ae14-55c2-11e6-9d69-8685daeee9e8.jpg)

**Comment by lightningfuzion2** [comment]
reffer >> [This](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/11) till the end.

you may have already got a version of python installed in your PC. if so.
change code in main.js:
pythonCmd = path.join(__dirname, 'pywin', 'python.exe');
change to
pythonCmd = path.join('C:/', 'Python27', 'python.exe');

**Comment by weirdohunt** [comment]
am I ment to run pokecli.py like in its own cmd window
![test3](https://cloud.githubusercontent.com/assets/20646791/17244277/63a108a0-55c4-11e6-8f2b-f40093eb4177.jpg)

ok ill give that a go

**Comment by weirdohunt** [comment]
ok found pywin ill give this a go

**Comment by weirdohunt** [comment]
![test4](https://cloud.githubusercontent.com/assets/20646791/17244484/7435805a-55c5-11e6-8f0e-91fa3e26f209.jpg)


this happen ?

**Comment by weirdohunt** [comment]
well it working but cant find it on map XD

**Comment by lightningfuzion2** [comment]
So it seems to be working fine rite ? just that the bot dose't catches any pokemon or spins pokestops rite ?

if that is the case follow [this](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/19) 

we know the problem but need to find a solution yet.

**Comment by weirdohunt** [comment]
I don't know if I my self did somethink wrong here 
but I manual download pgoapi and droped it here. 
install -r requirements.txt worked after i removed the first line
of this
-e git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi


![test6](https://cloud.githubusercontent.com/assets/20646791/17245876/05d2afaa-55cc-11e6-948f-d04a20c9ca2a.jpg)
feeling like somethinks missing

**Comment by lightningfuzion2** [comment]
you do need the 1st line.. but to get that working you need is GIT commands working in cmd, go [here](https://git-scm.com/download/win) to download, make sure do [this](http://i.stack.imgur.com/6KElW.png) while installing GIT

**Comment by weirdohunt** [comment]
thx for the help man but how do i use this ? how do I use this.
 -e git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi

**Comment by lightningfuzion2** [comment]
If its pulling the info and is just walking around with out doing any thing (catching or farming) then you need to do nothing more, rest will be solved by the developer as i am facing the same problem and others too. as this issue is mentioned [here](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/19)

**Comment by weirdohunt** [comment]
I cant see me char ;( walking around

**Comment by lightningfuzion2** [comment]
-e git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi
geopy==1.11.0
protobuf==3.0.0b4
requests==2.10.0
s2sphere==0.2.4
gpsoauth==0.3.0
protobuf-to-dict==0.1.0
googlemaps==2.4.4
colorama==0.3.7
enum34==1.1.6
pyyaml==3.11
haversine==0.4.5
polyline==1.3.1

all the above should be in the requirements.txt file placed in the gofbot dir,
once that is done go to gofbot directory, shift+right click in that dir, click on open command file here,
then type pip install -r requirements.txt in the cmd.
before doing the above make sure you have installed the git the way i mentioned above.
send the screen shot of any errors that you encounter.

**Comment by weirdohunt** [comment]
so pip install -r requirements.txt  hit a error with git alrdy installed tried this.

**Comment by lightningfuzion2** [comment]
could you please send the screen shot of the error ?

**Comment by weirdohunt** [comment]
![test7](https://cloud.githubusercontent.com/assets/20646791/17247071/c3a2b3ca-55d3-11e6-8143-de503d7819d0.jpg)

**Comment by lightningfuzion2** [comment]
yea same is with me. not sure whats wrong then try running the bot alone using pokecli.py with "mode"="all" in config.json  see if it works fine ? like moving around catching and farming?

**Comment by JVenberg** [comment]
I just pushed something the temporarily fix the mode bug

**Comment by lightningfuzion2** [comment]
Venberg is back in game ;)

**Comment by JVenberg** [comment]
Haha, I'll try my best to help out. The program is very rough right now. Eventually it will be packaged to prevent a lot of these installing errors

**Comment by weirdohunt** [comment]
![test8](https://cloud.githubusercontent.com/assets/20646791/17247179/d37cf14c-55d4-11e6-9edd-b2457fcea356.jpg)

**Comment by JVenberg** [comment]
That looks like a response error from the pokemon go servers not responding

**Comment by JVenberg** [comment]
You can try to run "python pokecli.py" in the gofbot directory to see if it happens there too

**Comment by lightningfuzion2** [comment]
Guru Venberg could you please teach me programming ? I am serious. please give me a way to PM you

**Comment by weirdohunt** [comment]
come back a same thing python pokcli.py 220, 206, 31, 169, 400 this time

**Comment by weirdohunt** [comment]
tried running the npm start again. got this  
![test9](https://cloud.githubusercontent.com/assets/20646791/17247337/dff52560-55d5-11e6-8192-a72747089b91.jpg)

**Comment by JVenberg** [comment]
That likely means that the pokemon go servers are down

**Comment by weirdohunt** [comment]
;( https://ispokemon.online/

**Comment by JVenberg** [comment]
I am getting the same errors, servers are down

**Comment by weirdohunt** [comment]
ok ive had enuff thx for the help, did notice all the config.json data's on one line now alought

**Comment by lightningfuzion2** [comment]
yea can we have each config on a new line ? /n ?
