### ISSUE TITLE
NO ISSUE BUT I STILL NEED HELP! 

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#201]
Can someone tell me what I should change, that the bot is collecting more pokestops? Because he is always standing on a point. Sorry for my English and I think I know what I should change but I'm worried that I could "destroy" it.

{
    "auth_service": "---",
    "username": "---",
    "password": "---",
    "location": "---",
    "gmapkey": "---",
    "libencrypt_location": "---",
    "tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "all",
                "first_evolve_by": "cp",
                "evolve_above_cp": 1000,
                "evolve_above_iv": 1,
                "logic": "or",
                "evolve_speed": 20,
                "use_lucky_egg": false
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                    "Pokeball": {
                        "keep": 100
                    },
                    "Potion": {
                        "keep": 10
                    },
                    "Super Potion": {
                        "keep": 20
                    },
                    "Hyper Potion": {
                        "keep": 30
                    },
                    "Revive": {
                        "keep": 30
                    },
                    "Razz Berry": {
                        "keep": 100
                    }
                }
            }
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70 **(?)**
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50 **(I should change this, right?)**
    },
    "websocket_server": false,
    "walk": 200, 
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false, **(what's that?)**
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1,
    "catch_randomize_spin_factor": 1,
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Example of always catching Rattata:": {},
        "// Rattata": {
            "always_catch": true
        }
    },
    "release": {
        "any": {
            "release_below_cp": 132,
            "release_below_iv": 0.5,
            "logic": "or"
        },
        "// Example of always releasing Rattata:": {},
        "// Rattata": {
            "always_release": true
        },
        "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
        "// Pidgey": {
            "keep_best_cp": 3
        },
        "// Example of keeping 2 stronger (based on IV) Zubat:": {},
        "// Zubat": {
            "keep_best_cp": 2,
            "keep_best_iv": 3
        },
        "// Also, it is working with any": {},
        "// any": {
            "keep_best_iv": 3
        },
        "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {}
    },
    "vips": {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {
            "catch_above_cp": 1200,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md

**Comment by MrAppleMania** [comment]
Thanks :)
