### ISSUE TITLE
My bot starts up, but then i get this message...

### ISSUE THREAD

**Issue by AlexTheCreator** [PokemonGoF/PokemonGo-Bot-Desktop#205]
_Issue without proper information won't be answered_
### Information
- OS: Windows 10
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs
  Is there anything i can do to make the bot run normally again? :/
  ![problem 1](https://cloud.githubusercontent.com/assets/21069759/17728389/5216551e-645f-11e6-8759-c35a04ed75c8.png)
  ![problem 2](https://cloud.githubusercontent.com/assets/21069759/17728394/5609333a-645f-11e6-92ef-008f34285242.png)

**Comment by pokeimsn239** [comment]
Same issue here.

**Comment by zecompadre** [comment]
Same issue here.

**Comment by ProjectBarks** [comment]
A lot of people have been getting that issue. We are working on a new release now where this will not be a problem

**Comment by ProjectBarks** [comment]
This is the same issue as #199. I am going to close to prevent duplicate issues
