### ISSUE TITLE
Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.

### ISSUE THREAD

**Issue by xydeown** [PokemonGoF/PokemonGo-Bot-Desktop#21]
when i run npm start i get this:

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/.linuxbrew/Cellar/node/6.3.1/bin/node" "/root/.linuxbrew/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log

I installed electron,node, all needed.
What to do?

**Comment by lightningfuzion2** [comment]
[read this issue](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/18)

**Comment by xydeown** [comment]
And read here the issue and take a look i already SAID I INSTALLED NODE AND ELECTRON PER THIS ISSUE:
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/18

So why you DONT read?

READ WHAT I SAY,PER https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/18 ITS STILL NOT WORKING TO ME

**Comment by JVenberg** [comment]
@xydeown You need to calm down. We are just trying to help. It does appear that electron is not installed correctly.

Did you already run "npm install electron-prebuilt -g"? If you did, can you send its response?

**Comment by xydeown** [comment]
https://s31.postimg.org/tqkxkww7v/29_07_16_15_53_37.png

i did this in pokemongo bot directory:
npm install electron-prebuilt -g

And got confirm 
https://s31.postimg.org/n0wh53vnv/29_07_16_15_57_20.png

So how to fix electron? i using ubunutu 14.04 x64

**Comment by JVenberg** [comment]
Can you install npm and node from here again?
https://nodejs.org/en/download/

**Comment by xydeown** [comment]
Yes,i did already few times the same:
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

then when finish:

sudo apt-get install -y nodejs

from this page:
https://nodejs.org/en/download/package-manager/

**Comment by xydeown** [comment]
Now i have this error:
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/.linuxbrew/Cellar/node/6.3.1/bin/node" "/root/.linuxbrew/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `cd ./gofbot/ && sudo pip install -r requirements.txt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'cd ./gofbot/ && sudo pip install -r requirements.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./gofbot/ && sudo pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log

**Comment by JVenberg** [comment]
Are you running npm install or npm start?

**Comment by xydeown** [comment]
npm install

**Comment by JVenberg** [comment]
What happens when you run npm start?

**Comment by xydeown** [comment]
I get this:

> PokemonGoBot@0.0.1-alpha start /var/www/html/PokemonGo-Bot-Desktop
> electron main.js

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/.linuxbrew/Cellar/node/6.3.1/bin/node" "/root/.linuxbrew/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log

Maybe i should change server? i use ubuntu 14.04 x64

**Comment by JVenberg** [comment]
Can you run "npm install electron-prebuilt -save" in the PokemonGo-Bot-Desktop directory?

**Comment by xydeown** [comment]
I tried before and now did again:
root@pokemongobot:/var/www/html/PokemonGo-Bot-Desktop# npm install electron-prebuilt -save

> electron-prebuilt@1.3.1 postinstall /var/www/html/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt
> node install.js

PokemonGoBot@0.0.1-alpha /var/www/html/PokemonGo-Bot-Desktop
└── electron-prebuilt@1.3.1

**Comment by JVenberg** [comment]
and npm start still fails?

**Comment by xydeown** [comment]
Yes still same errors:
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/.linuxbrew/Cellar/node/6.3.1/bin/node" "/root/.linuxbrew/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `cd ./gofbot/ && sudo pip install -r requirements.txt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'cd ./gofbot/ && sudo pip install -r requirements.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./gofbot/ && sudo pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log
root@pokemongobot:/var/www/html/PokemonGo-Bot-Desktop#

**Comment by xydeown** [comment]
I have no idea what is the reason,node pip phyton everyting installed

**Comment by JVenberg** [comment]
You just showed me the error for npm install instead of npm start, right?

**Comment by xydeown** [comment]
Yes

**Comment by JVenberg** [comment]
Did you run npm start?

**Comment by xydeown** [comment]
they give the same now i did npm start:

> PokemonGoBot@0.0.1-alpha start /var/www/html/PokemonGo-Bot-Desktop
> electron main.js

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/root/.linuxbrew/Cellar/node/6.3.1/bin/node" "/root/.linuxbrew/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log

**Comment by xydeown** [comment]
installing electeron not help to fix the errors

**Comment by xydeown** [comment]
I can change server if better,what recommended server settings? i can use anything else like CentOS fedora etc execpt windows

**Comment by JVenberg** [comment]
Can you install from https://nodejs.org/en/download/?
It might be because you have unsupported versions of npm and node

**Comment by JVenberg** [comment]
Right now you have node v6.3.1 and npm v3.10.3, and you need node v4.4.7 and npm v2.15.8)

**Comment by xydeown** [comment]
Ok one moment i will install older version

**Comment by xydeown** [comment]
Hmm i install 4.4.7 and its always installing v6 i don't know how to force it to install v4

**Comment by JVenberg** [comment]
Try 

```
npm install -g n
n 4.4.7
```

**Comment by xydeown** [comment]
still on v6..ok i got that is the issue for sure i will try setup all server from zero and will install thanks a lot for your help,i will put here message if didn't helped

**Comment by xydeown** [comment]
JVenberg still not working,i setup server from zero ubunutu 14.04 64bit,i installed node 4.4.7 from the link and all other related,i installed electeron,and when press npm start:
root@PokemonGoBot:/var/www/html/PokemonGo-Bot-Desktop# npm start

> PokemonGoBot@0.0.1-alpha start /var/www/html/PokemonGo-Bot-Desktop
> electron main.js

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
npm ERR! This is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/PokemonGo-Bot-Desktop/npm-debug.log
root@PokemonGoBot:/var/www/html/PokemonGo-Bot-Desktop#

What can i do now?

**Comment by vinc05** [comment]
i'have derbian 8 and have your problem ...

**Comment by xydeown** [comment]
Nothing help i tried everyting.
I do which electeron i can see electron is installed.
i used node version 4.4.7 like he said still not work
i dont know how to fix it..

**Comment by lightningfuzion2** [comment]
May be just may be when Linux is running npm install all the node-modules are being installed globaly instead of the pokemongo-Bot-desktop where they should actually be for the bot to run in the package directory in node_modules ?

try
*Launch from inside /PokemonGo-Bot-Desktop directory:

npm install -link

I am just trying to help here :)

**Comment by xydeown** [comment]
I am appreciate it,this didn't helped too.

**Comment by xydeown** [comment]
What system you use?

**Comment by lightningfuzion2** [comment]
oddly i use windows but did some research to come up with that.
sorry it did't help though.

**Comment by xydeown** [comment]
Thanks for try,

**Comment by rednka** [comment]
same error on windows xp sp3
