### ISSUE TITLE
I don't see the file

### ISSUE THREAD

**Issue by Billy880923** [PokemonGoF/PokemonGo-Bot-Desktop#211]
I don't see the file **# libencrypt.so** in pgoencrypt.tar.gz

**Comment by ericorruption** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt should have the compiled file.

**Comment by taco1124** [comment]
Did u make the file?

wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make

**Comment by Billy880923** [comment]
thanks

**Comment by Billy880923** [comment]
![default](https://cloud.githubusercontent.com/assets/21094562/17796537/bd241f5e-65f3-11e6-9114-90fddcc852df.PNG)

where?

**Comment by ericorruption** [comment]
@Billy880923 you should click the button to choose the encrypt file you downloaded for your platform (or compiled yourself).

**Comment by Billy880923** [comment]
where can download this file ?

**Comment by ericorruption** [comment]
@Billy880923 https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/211#issuecomment-240907841

**Comment by Billy880923** [comment]
first use

**Comment by Billy880923** [comment]
sorry

**Comment by Billy880923** [comment]
choose the encrypt file ?? I don't find on my pc

**Comment by Billy880923** [comment]
![default](https://cloud.githubusercontent.com/assets/21094562/17797305/6dafce26-65fa-11e6-9df3-4d6822b6294b.PNG)

help me!!

**Comment by Outpox** [comment]
@Billy880923 : Just read the error?
