### ISSUE TITLE
maximum recursion depth

### ISSUE THREAD

**Issue by elvishp2006** [PokemonGoF/PokemonGo-Bot-Desktop#219]
![2016-08-21](https://cloud.githubusercontent.com/assets/7463100/17835648/9f0664a0-674c-11e6-9e8a-78d837beee0e.png)
### Steps to Reproduce

On application load.
### Information
- OS Windows 10

**Comment by rsilveiradesouza** [comment]
Same here. =X

**Comment by GodZZila** [comment]
me2

**Comment by KDA809** [comment]
what settings did you have before getting that error ?

**Comment by GabrielTofvesson** [comment]
This happened to me when I used the 64 bit libencrypt. I found that switching to encrypt32bit.dll (despite having a 64bit OS) fixed the issue.

**Comment by GodZZila** [comment]
idd the 32bit dll is the solution

**Comment by elvishp2006** [comment]
Yes, this is the solution, ty guys :)
