### ISSUE TITLE
I have a bit of problem here

### ISSUE THREAD

**Issue by lifeofbolo** [PokemonGoF/PokemonGo-Bot-Desktop#22]
Can anybody help me with this? I'm pretty new to programming and i would love to get this up and running. I'm trying to make it work on my mac :-)

<img width="823" alt="skaermbillede 2016-07-29 kl 17 11 50" src="https://cloud.githubusercontent.com/assets/20727032/17253178/ea8ba52e-55af-11e6-9625-43c2a5fba12b.png">

**Comment by JVenberg** [comment]
You need to run npm install inside of the PokemonGo-Bot-Desktop directory

**Comment by lifeofbolo** [comment]
It's not working quite properly right now. Is it the servers?

<img width="792" alt="skaermbillede 2016-07-29 kl 18 31 41" src="https://cloud.githubusercontent.com/assets/20727032/17255756/dbcde262-55ba-11e6-943c-8d1836f7deb0.png">

**Comment by JVenberg** [comment]
Yeah, that means the servers are busy. They have been pretty bad lately. It makes testing really difficult

**Comment by lifeofbolo** [comment]
oh okay :-) but thanks man!

**Comment by lifeofbolo** [comment]
I have another issue with another app i'm trying to run. Do you think you can help?

**Comment by lifeofbolo** [comment]
What does this mean?
<img width="825" alt="skaermbillede 2016-07-29 kl 19 04 52" src="https://cloud.githubusercontent.com/assets/20727032/17256805/63983856-55bf-11e6-9526-f1fe907210e8.png">

**Comment by Franckrst** [comment]
i have same error

**Comment by JVenberg** [comment]
This is another sign that the servers are busy

**Comment by Franckrst** [comment]
I have this error  : Python: [2016-07-31 14:57:40] [#]

Python: Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>

Python:     main()
  File "./pokecli.py", line 206, in main
    bot.start()
  File "/Users/fruysshaert/ownCloud/pokemongo/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/**init**.py", line 32, in start

Python:     self.stepper = Stepper(self)
  File "/Users/fruysshaert/ownCloud/pokemongo/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/stepper.py", line 31, in **init**

Python:     self.steplimit2 = self.steplimit*_2
TypeError: unsupported operand type(s) for *_ or pow(): 'NoneType' and 'int'

**Comment by lifeofbolo** [comment]
@JVenberg Why won't it import the gpxpy file? 

Python:     from follow_path import FollowPath
  File "/Users/kennethbolo/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/follow_path.py", line 3, in <module>
    import gpxpy
ImportError: No module named gpxpy
