### ISSUE TITLE
changing location in desktop app

### ISSUE THREAD

**Issue by kiss12andras** [PokemonGoF/PokemonGo-Bot-Desktop#221]
Hello,
so i just started using the pikabot and i was wondering how i could change the location. i used the given encrypt file since im not a programmer. is there any way to change it in the app?
i use a macbook air with the newest os.
thanks for the help!

_Issue without proper information won't be answered_
### Information
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by ericorruption** [comment]
you can pass `latitude, longitude` values in the start screen. You can grab those values from google maps if you right-click a place and go `what's here?`

You can't choose a new location (yet?) from inside the app though, if that's what you wanted.
