### ISSUE TITLE
Help please?

### ISSUE THREAD

**Issue by roshcamlian** [PokemonGoF/PokemonGo-Bot-Desktop#226]
I'm trying to figure out how I could edit my config or at least make one. I'm using Windows. Read something about the edit for the config would only work for Macs or something like that. I really know nothing about scripts and all these, so I could only do searches and ask then stumbled upon this https://pokemongof.github.io/botConfig/#/ I made one but even the slightest edits won't run in the program, it just closes and takes me back to the log in. So I was wondering if https://pokemongof.github.io/botConfig/#/ doesn't work? Or that I might be doing something wrong? But if anyone could suggest any other way too, I would really be grateful. I'd do anything for an Evolve config please ;-;

PS, I edited the config.json I had on my laptop, opened it with a WordPad. I screwed up with that one too. Read after that there isn't a way reverting it back to .json ( / changing the default launcher for a the file ) so now I have to use this desktop instead to use the program and then play back on the laptop :(
HALP PRETTY PRETTY PLEASE~? ;-;

**Comment by KDA809** [comment]
custom config.json file bro - https://github.com/iiCe89/PokemonGo-bot-config just download and place in your config folder 👍

**Comment by roshcamlian** [comment]
@iiCe89 
![whoops](https://cloud.githubusercontent.com/assets/21103035/17875398/6f572708-6904-11e6-91d5-6f0dfddadcaf.png)
and then the config released all the pokemons I was going to evolve for to gain experience ;-;

**Comment by KDA809** [comment]
Config file works as lots of others have used with no issues we tested it earlier today @roshcamlian

**Comment by KDA809** [comment]
it will also release all pokemon CP 350 or lower and replace with Candy so you do not max out how many pokemon you have

**Comment by roshcamlian** [comment]
@iiCe89 I did see it did work somehow yes, but that error just popped out so it's some sort of issue for me at least right?

I do want and like the idea of not maxing out the pokemon I have as well of course, but it did released the lower CP of pokemons to evolve for exp, as not all Pidgeys for example have a higher CP than 350 :/

and also the config spams the Lucky Eggs too ;-;

**Comment by mrincredible2017** [comment]
That error came up for me earlier too about the google access token.

**Comment by roshcamlian** [comment]
@mrincredible2017 re-run'd the application and luckily it didn't came up again. Maybe because I reverted back the config to the original one, or either because I reinstalled the whole application. Couldn't quite remember anymore, couldn't keep track of everything I've been doing and still am doing just to get a hold of a good configuration anymore lmao, ugh.

**Comment by mrincredible2017** [comment]
No reason to change anything or reinstall mate it just goes after some time.

**Comment by roshcamlian** [comment]
Well.. I really have nooo idea at all lmao. If you only knew. Stumbled upon this site on a youtube video for IV renamer.. scrolled down, scrolled, clicked links on Credits, scrolled, scrolled, clicked links on credits.. haha
I downloaded every software I thought that might be useful while playing. I'm just an ordinary person who wants to play Pokemon GO at home trying to reach max level. :p

**Comment by mrincredible2017** [comment]
Absolutely dude, that's why we are all here :)

**Comment by roshcamlian** [comment]
Hahaha but idk sometimes these people be talking script-language and the other guy understands it right away xD

and also btw I remembered that I might have skipped few steps like git commands or npm's or updates. But then again, I really have nooo idea. x.x

**Comment by KDA809** [comment]
hey bud i will be changing config file around today at work an testing out , so i will switch lucky egg off also

**Comment by roshcamlian** [comment]
@iiCe89 Where do you change stuff for the config? or how do you change them?

**Comment by mrincredible2017** [comment]
Hi @iiCe89 what I meant is at pokestops I am never gaining lucky eggs, so I don't ever acquire any to use them... Any ideas why?

I've also made a small change myself I've made the logic 'and' instead of or for the release.

 "release": {
        "any": {
            "release_below_cp": 300,
            "release_below_iv": 0.6,
            "logic": "and"

**Comment by roshcamlian** [comment]
@mrincredible2017 You don't and cannot obtain "Lucky Egg"s through spinning pokestops. You might or could be referring to normal pokemon Eggs that do hatch for pokemons instead? The "Lucky Egg"s are for double EXP gain for 30 minutes.

And also how do you make changes for your config?

**Comment by KDA809** [comment]
@mrincredible2017 lucky eggs are only obtained either through levelling up reward or by microtransactions only , the reason for setting lucky egg to true is if you do have them the Bot will activate and help double your XP up

**Comment by KDA809** [comment]
@roshcamlian you can open up the config.json file using editor i use Sublime and you can find futher documentation here - https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md 

**_also i wont be adding anymore to config.json file as i unfortunately dont have the time with full time DEV job and i also read that new offical pokemonGo update will kill off all Tracker & bots so its not worth my time**_

**Comment by roshcamlian** [comment]
@iiCe89 Thank you. Are you using Windows for OS as well? Should I just search for "Sublime" in google and download it instead? Because I was thinking that maybe you are using Mac that's why you could edit .json files. I mean I could edit the config.json file but not save it into a .json file, as I couldn't open a .json file with any .json default edit launcher but with a normal WordPad instead that would not save the scripts into .json after editing stuff.

**Comment by KDA809** [comment]
@roshcamlian im using Dell machine currently at work and i have Macbook pro at home i used both to edit - https://www.sublimetext.com/ download this and open config.json file in this it will save as .json file also :)

**Comment by mrincredible2017** [comment]
@iiCe89 D'oh! Totally forgot!
