### ISSUE TITLE
Shows 2 error popups and then quit

### ISSUE THREAD

**Issue by derendiaev** [PokemonGoF/PokemonGo-Bot-Desktop#229]
**Expected Behavior**
PokemonGo-Bot is working

**Actual Behavior**
After logging in it shows 2 error popups and sends back to the first screen. Yesterday it worked fine, nothing changed in code.

**Information**
- MacOS 10.11.5

Popoup screens: 
1st https://infinit.io/_/M6n3LKH.png
2nd https://infinit.io/_/32pTnqt.png

**Comment by luckofthelefty** [comment]
I've noticed these two errors when the account being used is banned. Try logging in to the account on mobile. If you see something along the lines of the picture below, its likely you have been banned in some fashion. ![PokemonBan](https://i.ytimg.com/vi/b4adDht9U3E/maxresdefault.jpg)

**Comment by derendiaev** [comment]
Thanks @luckofthelefty, i think it's really a ban)
I guess, i can give up on this account?

**Comment by Outpox** [comment]
If you've got this result on mobile then yes you can forget this account.
