### ISSUE TITLE
Get inventory error only happens some times while starting.

### ISSUE THREAD

**Issue by lightningfuzion2** [PokemonGoF/PokemonGo-Bot-Desktop#23]
![image](https://cloud.githubusercontent.com/assets/20586485/17258946/eed0b11a-55e6-11e6-89c8-274eff89d07e.png)

**Comment by JVenberg** [comment]
This appears to be an issue with the bot. I have had success with the new development version. Try updating PokemonGo-Bot-Desktop

**Comment by chienkira** [comment]
I had same error. I just ignored it, press Ctrl+C to interrupt and run npm start again and it's working.
