### ISSUE TITLE
PikaBot stop working

### ISSUE THREAD

**Issue by CyyRus** [PokemonGoF/PokemonGo-Bot-Desktop#231]
I'm not sure if its because of the recent update that i hear is circulation or if its another issue but mine won't log in with out displaying an error in the python bot
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by KDA809** [comment]
i couldn't login either with both gmail accounts today an more an more people are saying new updates will block all bot apps an tracker sites for good i've stopped using Bot don't really wanna lose both my decent accounts lol

**Comment by Outpox** [comment]
Try logging with your phone, if you can't connect with an error message looking like `Cannot fetch data from server` then your account got banned.

**Comment by CyyRus** [comment]
i can log into my account on my phone... but the pika bot just won't
start... it says it logs in and every thing but right after it brings up
the BIG error
