### ISSUE TITLE
release

### ISSUE THREAD

**Issue by roshcamlian** [PokemonGoF/PokemonGo-Bot-Desktop#234]
just want to confirm if there is an `and` option for `logic` in `release`? I am sincerely sorry if I keep asking random things too much maybe. Since I am very new to these stuff and couldn't check it myself as I really have no idea. iNub rly sry :/

_and when does default trigger_ `"release"` _too? sry forgot to mention :/_

**Comment by Outpox** [comment]
Check the [bot's documentation](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#release-configuration).  
This repo is dedicated to the application which runs the bot, not the bot itself.  
That means you'll have more luck [here](https://github.com/PokemonGoF/PokemonGo-Bot/issues) :+1:

**Comment by roshcamlian** [comment]
@Outpox oh okay I get it now. thank you
