### ISSUE TITLE
How do we set the config to Evolve all Ratata's and Pidgeys?

### ISSUE THREAD

**Issue by mrincredible2017** [PokemonGoF/PokemonGo-Bot-Desktop#239]
What do we need to set in the config.json to automatically evolve all rattatas and pidgeys, then automatically exchange the evolved ratatats and pidgeys and rinse and repeat?

**Comment by Outpox** [comment]
As your other issue #240, you should ask your question on [slack](https://pokemongo-bot.slack.com/) in the help or configs channel.
