### ISSUE TITLE
Bot Status doesn't show Pokémon names! [OS X]

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#241]
[https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/230](url)
Can someone fix this for OS X? Tried to find anything that looked not right but didn't find anything.

**Comment by Outpox** [comment]
If you want to do the same as  #230 that you linked, you just have to reproduce the process.  
JavaScript (in this case) is not OS dependent.
