### ISSUE TITLE
Transfer Pokemon?

### ISSUE THREAD

**Issue by Pwntastickevin** [PokemonGoF/PokemonGo-Bot-Desktop#247]
Any way The bot can transfer all the weak CP pokemon?

**Comment by mrincredible2017** [comment]
Yes just edit the config.json

**Comment by mrincredible2017** [comment]
When you say 'all weak' under what CP/IV do you mean?

I.e by weak do you mean under 50% IV? or under say 300 cp?

**Comment by danielocampbells** [comment]
which part of the config.json must be set? sorry buy my english isn't good enough, i want too to transfer all repeat pokemon and keep only two best!

**Comment by danielocampbells** [comment]
maybe is on this part??? 
 l
 l
 l
V

 "catch_randomize_reticle_factor": 1,
    "catch_randomize_spin_factor": 1,
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Example of always catching Rattata:": {},
        "// Rattata": {
            "always_catch": true
        }
    },
    "release": {
        "any": {
            "release_below_cp": 0,
            "release_below_iv": 0,
            "logic": "or"
        },
        "// Example of always releasing Rattata:": {},
        "// Rattata": {
            "always_release": true
        },
        "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
        "// Pidgey": {
            "keep_best_cp": 3
        },
        "// Example of keeping 2 stronger (based on IV) Zubat:": {},
        "// Zubat": {
            "keep_best_cp": 2,
            "keep_best_iv": 3
        },
        "// Also, it is working with any": {},
        "// any": {
            "keep_best_iv": 3
        },
        "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {}

i want to continue catch all pidgeys ratatas zubats etc for exp, but my pokemons bag full too fast!

**Comment by mrincredible2017** [comment]
So tell me what exactly you wanna do and I'll tell you the code to change.

**Comment by danielocampbells** [comment]
for example, i want to transfer all the pidgeys repeat, also wanna do with all pokemons, i keep only two of them, so in example of pidgeys, how set the config.json ! for transfer all and keep only 2, with out necessary login in app for transfer handmade one bye one

**Comment by mrincredible2017** [comment]
For pidgey for example;

See this line;

```
    "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
    "// Pidgey": {
        "keep_best_cp": 3
    },
```

remove //

and change "keep_best_cp": 3 

into:

"keep_best_cp": 2

**Comment by mrincredible2017** [comment]
so it should be 

```
"Example of keeping 3 stronger (based on CP) Pidgey:": {},
"Pidgey": {
    "keep_best_cp": 2
},
```

**Comment by danielocampbells** [comment]
ok for example if has been on 3, suppose that in theory i only have 3 pidgey, right ?

**Comment by danielocampbells** [comment]
but i have a lot of pidgeys already :/

**Comment by mrincredible2017** [comment]
It is set to three but when you keep the // in there it disables this line of code :)

So if you remove the // it will enable that. So save the config file, quit the program, start the program again and it will remove all pidgeys apart from the best 2 :)

**Comment by danielocampbells** [comment]
ohhhhh well let me see

**Comment by danielocampbells** [comment]
oh master thanks !!! its working so fucking good now, lol i don't know much about code, only i can read and understand. 

GRACIAS

**Comment by mrincredible2017** [comment]
De nada :)

**Comment by mrincredible2017** [comment]
This issue can now be closed.
