### ISSUE TITLE
Bot Stucks on start

### ISSUE THREAD

**Issue by flawnn** [PokemonGoF/PokemonGo-Bot-Desktop#250]
I am on Mac OS Yosemite, and it happened since the new pull. i dunnow why, but the bot is working
### Expected Behavior

Electron Helper has to but stucks
### Actual Behavior

I become also this fail message:
`Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: client.js:82:19.
    at BrowserWindow.callIntoRenderer (/Users/nevinpeters/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:189:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
    at Object.showErrorBox (/Users/nevinpeters/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/dialog.js:188:33)
    at process.<anonymous> (/Users/nevinpeters/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:64:10)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:262:26)
`
Desktop Electron Helper stucks, but bot is working
### Steps to Reproduce

-Start BOT
### Information
- Mac OS
- git commit: cc8863cb6242731a4837a71fd36e951f8497d11e
- APP LOG:

module.js:442 Uncaught Error: Cannot find module './picker.js'
module.js:442 Uncaught Error: Cannot find module './modules/const.js'
materialize.js:3 Uncaught ReferenceError: Materialize is not defined
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.woff Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.woff Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.ttf Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.ttf Failed to load resource: net::ERR_FILE_NOT_FOUND
client.js:27 [2016-09-04T10:18:55.738Z] [electron-connect] [client: 1] connected server

**Comment by Outpox** [comment]
Which "new pull" are you talking about?  
Please read the issue template, under "Information" there's `Git commit ( to get git commit run git log -1 --format="%H")` that you didn't even bothered to fill or remove.

**Comment by flawnn** [comment]
Here you are xD

![lol](https://cloud.githubusercontent.com/assets/19386703/18218297/02802a4c-7162-11e6-9758-829e07550938.jpg)

**Comment by NightScap3** [comment]
And it is stucking, how i said. Doesnt show anything, and when i refresh it it comes a white screen and again the stucking screen

**Comment by NightScap3** [comment]
module.js:442 Uncaught Error: Cannot find module './picker.js'
module.js:442 Uncaught Error: Cannot find module './modules/const.js'
materialize.js:3 Uncaught ReferenceError: Materialize is not defined
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.woff Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.woff Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Bold.ttf Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/nevinpeters/Documents/PokemonGo-Bot-Desktop/build/fonts/roboto/Roboto-Regular.ttf Failed to load resource: net::ERR_FILE_NOT_FOUND
client.js:27 [2016-09-04T10:18:55.738Z] [electron-connect] [client: 1] connected server


###this is the console

**Comment by flawnn** [comment]
#128 I have the same..... but nothing works

**Comment by Outpox** [comment]
Did you even read what I wrote?

**Comment by flawnn** [comment]
yes, i did. I wrote the git commit and even the app log. i dont now what you mean
Let us say it so.... my Bot doesnt finds the font folder
