### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by IrishReign** [PokemonGoF/PokemonGo-Bot-Desktop#255]
Sorry to have to keep writing these, but my bot has seemed to stop working. I has stopped gathering xp and farming pokemon. I have no clue why it is doing this. Thanks

Mac osx

**Comment by IrishReign** [comment]
I don't know if its just my account or what, but a different account works fine.

**Comment by KDA809** [comment]
does your accounthave two step auth ?

**Comment by IrishReign** [comment]
@iiCe89 What is 2 step auth

**Comment by IrishReign** [comment]
I get the "Session Stale message"

**Comment by IrishReign** [comment]
@iiCe89 now it just shows me this
![screen shot 2016-09-04 at 3 48 08 pm](https://cloud.githubusercontent.com/assets/21983686/18234355/13b71ea0-72b7-11e6-8c10-d1aa00028c73.png)

**Comment by Outpox** [comment]
Is it still an issue?

**Comment by IrishReign** [comment]
@Outpox No not anymore but my bot sometimes gets stuck on the "walking sign"
