### ISSUE TITLE
Transferring duplicate pokemon

### ISSUE THREAD

**Issue by phipotts** [PokemonGoF/PokemonGo-Bot-Desktop#256]
Can someone please help me with the config.json . i want to be able to make it so that I can make duplicates automatically transferred. either a copy and paste or a description would be brilliant

thanks.

**Comment by flawnn** [comment]
Make:

},
    "release": {
        "Ratatta": {
            "keep_best_iv": 1
 },

**Comment by KDA809** [comment]
Documentation - https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md
