### ISSUE TITLE
New Type of Soft Ban?

### ISSUE THREAD

**Issue by IrishReign** [PokemonGoF/PokemonGo-Bot-Desktop#259]
This happens maybe once or twice a day and lasts for about an hour. I feel like its some sort of new ip ban because the map stops loading on my computer and phone. Even if the map on my phone was loaded previously I can't catch pokemon or spin pokestops. Although if I use cell service it works... I have checked whether it was my wifi but that is a negative, my wifi has a download speed of about 300 mbs per second and was working through out this. It happens to my friend (Who I helped download the bot as well) and seems to be random. Whenever it happens the bot gets stuck on the "Walking message"

Mac El Cap

**Comment by Outpox** [comment]
This is related to your other issue #257 
There's no need to open many thread for the same thing.
