### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by Aaranaw** [PokemonGoF/PokemonGo-Bot-Desktop#26]
Hi, will you be implementing support for multiple accounts?

**Comment by xydeown** [comment]
How u successed to run this?
What system u using?

**Comment by ProjectBarks** [comment]
It is not in our project plan to support multiple accounts. The goal of this project is to make an easy accessible project. However the point of the the command line is to make the best functional bot. If you want support for multiple bots users should use the command line version instead.
