### ISSUE TITLE
Coordinates Error?

### ISSUE THREAD

**Issue by IrishReign** [PokemonGoF/PokemonGo-Bot-Desktop#260]
_Issue without proper information won't be answered_
### Expected Behavior

The Bot to telleport to the selected coordanates.
### Actual Behavior

I tried to put in coordantates to "fort mason" a squirtle nest. It teleported my to south korea instead of the naval base in san francico
### Information
- OSX El Cap

**Comment by flawnn** [comment]
maybe, a number you didnt copy? this happened also to me 😄

**Comment by KDA809** [comment]
can also get u soft banned and cause pokemon to vanish if your teleporting from location to another so risk losing them

**Comment by Outpox** [comment]
The bot version bundled with the app doesn't support location name, you have to use coordinates.
