### ISSUE TITLE
Adding Lure Module usability on bot

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Bot-Desktop#269]
I know this isn't a issue, but I presume adding a lure module option to the bot that the client will retrieve far more rare pokemon while AFKing. I'm new to using Python and would love to become a contributor to this repository. If this idea has already been implemented into the base of the desktop bot and I am unaware, please inform me and close this post.

Thanks,

William

**Comment by Outpox** [comment]
Thanks for your interest in this project, altough this repository is for the desktop app of the bot, which in itself is just a wrapper (made with web technlogies, so html+css+js and electron) which bundle the bot that you can find [at this address](https://github.com/PokemonGoF/PokemonGo-Bot).
