### ISSUE TITLE
ERROR ELECTRON MAIN

### ISSUE THREAD

**Issue by vinc05** [PokemonGoF/PokemonGo-Bot-Desktop#29]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart PokemonGoBot@0.0.1-alpha
6 info start PokemonGoBot@0.0.1-alpha
7 verbose unsafe-perm in lifecycle true
8 info PokemonGoBot@0.0.1-alpha Failed to exec start script
9 error PokemonGoBot@0.0.1-alpha start: `electron main.js`
9 error Exit status 127
10 error Failed at the PokemonGoBot@0.0.1-alpha start script.
10 error This is most likely a problem with the PokemonGoBot package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     electron main.js
10 error You can get their info via:
10 error     npm owner ls PokemonGoBot
10 error There is likely additional logging output above.
11 error System Linux 2.6.32-openvz-042stab116.2-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /root/PokemonGo-Bot-Desktop
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

THIS IS LOG i don't know problem i watch all issues and i install all , and don't go i form italy sorry for bad english thanks!

**Comment by xydeown** [comment]
I have the same,still no fix i use ubuntu 14.04 64.
