### ISSUE TITLE
Pokemon evolution check

### ISSUE THREAD

**Issue by A-Charvin** [PokemonGoF/PokemonGo-Bot-Desktop#32]
An option to control evolution of Pokemon to reduce lose of candies. 
For level above
Option to have the option to evolve higher version of Pokemon. 
Prevention of candy lose due to evolution of lower sets instead of higher ones.

Evolve :  
Insted of wasting candies to evolve.
Poliwag -> Poliwhirl | Candies = 25
The evolution should focus on
Poliwhirl -> Poliwrath | Candies = 100

**Comment by JVenberg** [comment]
I agree, ideally we will be able to edit all options in the config files eventually
