### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by sunshinebuttz** [PokemonGoF/PokemonGo-Bot-Desktop#33]
The directory '/Users/Username/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Username/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! PokemonGoBot@0.0.1-alpha postinstall: `cd ./gofbot/ && sudo pip install -r requirements.txt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha postinstall script 'cd ./gofbot/ && sudo pip install -r requirements.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./gofbot/ && sudo pip install -r requirements.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maswerczek/Downloads/PokemonGo-Bot-Desktop-development/npm-debug.log

I have tried a few times to install the desktop vertion of the pokemon Go bot but I keep getting this error. Anyone else having this issue?

**Comment by JVenberg** [comment]
What operating system are you using?

**Comment by JVenberg** [comment]
If you are on windows, try the newests version

**Comment by AwesomeGalS2** [comment]
Well, I had this problem. I checked the gobot and it was empty so I came back to here and checked it. It directed me to a bot

**Comment by JVenberg** [comment]
@AwesomeGalS2 You need to clone the desktop app with:
`git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop`
This will get all submodules
