### ISSUE TITLE
Can't Enter and Map Live is Blank

### ISSUE THREAD

**Issue by AwesomeGalS2** [PokemonGoF/PokemonGo-Bot-Desktop#35]
`
Uncaught Exception:
Error: ENOENT: no such file or directory, rename '/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/gofbot/web/userdata.js.example' -> '/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/gofbot/web/userdata.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at renameFiles (/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/main.js:259:12)
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/main.js:263:5
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:138:14
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:106:16
    at Server.onListen (/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop-development/node_modules/portfinder/lib/portfinder.js:35:5)`

What do I need to solve this?

**Comment by JVenberg** [comment]
What is currently in your PokemonGo-Bot-Desktop-development/gofbot/web/ directory?

**Comment by JVenberg** [comment]
It looks like you didn't install the submodules for the repo. You need to run:
`git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop`
This will install the bot and web interface

**Comment by AwesomeGalS2** [comment]
Tried what you said. 
`Uncaught Exception:
SyntaxError: Unexpected token } in JSON at position 1770
    at Object.parse (native)
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/main.js:259:25
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:138:14
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:106:16
    at Server.onListen (/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:35:5)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)`
