### ISSUE TITLE
libXss.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot-Desktop#37]
/home/PokemonGo-Bot-Desktop/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

npm ERR! Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! PokemonGoBot@0.0.1-alpha start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PokemonGoBot package,npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PokemonGoBot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PokemonGoBot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/PokemonGo-Bot-Desktop/npm-debug.log
[root@vultr PokemonGo-Bot-Desktop]#

**Comment by JVenberg** [comment]
Can you try downgrading to node v4.4.7 and npm v2.15.8?
