### ISSUE TITLE
Can't start 

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot-Desktop#38]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle PokemonGoBot@0.0.1-alpha~prestart: PokemonGoBot@0.0.1-alpha
6 silly lifecycle PokemonGoBot@0.0.1-alpha~prestart: no script for prestart, continuing
7 info lifecycle PokemonGoBot@0.0.1-alpha~start: PokemonGoBot@0.0.1-alpha
8 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: unsafe-perm in lifecycle true
9 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/PokemonGo-Bot-Desktop/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle PokemonGoBot@0.0.1-alpha~start: CWD: /home/PokemonGo-Bot-Desktop
11 silly lifecycle PokemonGoBot@0.0.1-alpha~start: Args: [ '-c', 'electron main.js' ]
12 silly lifecycle PokemonGoBot@0.0.1-alpha~start: Returned: code: 1  signal: null
13 info lifecycle PokemonGoBot@0.0.1-alpha~start: Failed to exec start script
14 verbose stack Error: PokemonGoBot@0.0.1-alpha start: `electron main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid PokemonGoBot@0.0.1-alpha
16 verbose cwd /home/PokemonGo-Bot-Desktop
17 error Linux 3.10.0-327.22.2.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error PokemonGoBot@0.0.1-alpha start: `electron main.js`
22 error Exit status 1
23 error Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the PokemonGoBot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs PokemonGoBot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls PokemonGoBot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by JVenberg** [comment]
Can you try downgrading to node v4.4.7 and npm v2.15.8?
