### ISSUE TITLE
Nothing happens after logging in

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot-Desktop#40]
After i log in and fill in the coords and click "apply" nothing happens the map stays blank

The pokemon, items tabs are working but nothing actually happens

**Comment by JVenberg** [comment]
What does the console say?

**Comment by Pockos** [comment]
With same problem:

Starting Python process...
Got open port: 8000
Bot path: C:\Poke\PokemonGo-Bot-Desktop\gofbot
python ./pokecli.py
Bot path: C:\Poke\PokemonGo-Bot-Desktop\gofbot\web
python serveit.py 8000
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions

server started!

**Comment by JohnnyOmm** [comment]
I get this same issue!

**Comment by cloudleon** [comment]
same here

**Comment by Parth6182** [comment]
Yes all that stuff happens and after that the actual bot / map opens up but nothing works / the map is just a plain world map

**Comment by JVenberg** [comment]
This is because the bot is failing to run because it does not have the required python modules. Try running npm install again

**Comment by VoxNephilia** [comment]
I ran npm install a few times and still get the issue.

```
Starting Python process...
Got open port: 8000
Bot path: C:\Users\AJ\Downloads\PokemonGo-Bot\PokemonGo-Bot-Desktop\gofbot
python ./pokecli.py
Bot path: C:\Users\AJ\Downloads\PokemonGo-Bot\PokemonGo-Bot-Desktop\gofbot\web
python serveit.py 8000
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions

server started!
```

It says "Logged in as .. Loading.." for a while then changes to say my email. Setting anything and hitting apply does nothing.

Might be worth noting that I'm on Windows 10 and installed node.js separately. Perhaps it's unable to find it?

**Comment by Parth6182** [comment]
Im on a mac but i get the same issue ^

**Comment by comfortedbasher** [comment]
same

**Comment by Yutsa** [comment]
@JVenberg The same things is being discussed over at #51 if you want some more information
