### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by malafronte-james** [PokemonGoF/PokemonGo-Bot-Desktop#43]
Python: [11:03:51]  [X] Login Error, server busy 
[11:03:51]  [X] Waiting 10 seconds to try again 

I've checked to see if the login servers are down, and they have been stable.

**Comment by g2384** [comment]
You can either 1) Check the network connection, 2) Try it few minutes later, or 3) Download the code again without any amendment.

Related issue [https://github.com/PokemonGoF/PokemonGo-Bot/issues/2174](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2174)

**Comment by sniok** [comment]
Not a desktop bot issue
