### ISSUE TITLE
pgoapi - "Could not find a tag or branch"

### ISSUE THREAD

**Issue by CorentinDy** [PokemonGoF/PokemonGo-Bot-Desktop#47]
Hi ,
when i run install i've this error , same with the standard version of the bot (without desktop) 

`Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b) to ./src/pgoapi
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.
`

any idea how to fix ?

**Comment by LasseSkogland** [comment]
It's not a error, this is normal.

**Comment by MartinThoma** [comment]
See https://stackoverflow.com/a/13754517/562769

**Comment by nbq** [comment]
@MartinThoma You picked a VERY old, and closed, issue to respond to.
