### ISSUE TITLE
Page does not update info

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot-Desktop#48]
No information (caught, map, exp, traveled dist) is updated at all after about 1 min.
Environment: Ubuntu 16.04(64bit). All dependencies are up-to-date.
Commit: 4dcfdddef16ee02c071b3e35dfe35f1a7b028224

**Comment by JVenberg** [comment]
This means that the bot failed to run. What is the console output?

**Comment by g2384** [comment]
I can see the bot is running as normal, collecting things and catching Pokemon. Only no visual update.

Or, how about add a REFRESH button?

**Comment by vardius** [comment]
Same on Windows, also tools -> refresh does not work, when i refresh aplication go white screen when at console bot is running.

**Comment by sniok** [comment]
@Vardius This was a Python server bug. We got rid of it. Update to the latest version

**Comment by flawnn** [comment]
no, i have the problem
