### ISSUE TITLE
Still can't get in

### ISSUE THREAD

**Issue by AwesomeGalS2** [PokemonGoF/PokemonGo-Bot-Desktop#50]
`Uncaught Exception: SyntaxError: Unexpected token } in JSON at position 1770 at Object.parse (native) at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/main.js:259:25 at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:138:14 at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:52:16 at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:269:32 at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:44:16 at /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:106:16 at Server.onListen (/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:35:5) at Server.g (events.js:286:16) at emitNone (events.js:86:13)`

**Comment by JVenberg** [comment]
Can you try to get a fresh install of the PokemonGo-Bot-Desktop?

**Comment by AwesomeGalS2** [comment]
Okay, I will try

**Comment by AwesomeGalS2** [comment]
Having problem..
`> PokemonGoBot@0.0.1-alpha start /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop

> electron main.js

2016-08-01 13:54:11.197 Electron Helper[1877:141121] Couldn't set selectedTextBackgroundColor from default ()
Starting Python process...
Got open port: 8000
Bot path: /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Bot path: /Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/gofbot/web
python serveit.py 8000
Python: Traceback (most recent call last):
  File "./pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/Amuyea/Desktop/NEWBOTDESKTOP/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/**init**.py", line 14, in <module>
    from pgoapi.utilities import f2i, get_cell_ids
ImportError: cannot import name get_cell_ids

server started!
`

Is there a fix for it or fix the files?

**Comment by JVenberg** [comment]
Did you run npm install?

**Comment by JVenberg** [comment]
You can also try the new release to bypass all these issues
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases

**Comment by AwesomeGalS2** [comment]
Yes.

Yeah, I tried it. No problem but its not doing anything

**Comment by Rlewisrlou666** [comment]
I get this error can someone point me to the proper setup instructions please.

![snip20160803_7](https://cloud.githubusercontent.com/assets/20677921/17365151/63baad12-597c-11e6-9c38-d45da4343b56.png)

**Comment by sniok** [comment]
@Rlewisrlou666  Seems like you are missing some python packeges. Try running `npm install`

**Comment by Rlewisrlou666** [comment]
Cheers it seems to be working now.
