### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by subzerofun** [PokemonGoF/PokemonGo-Bot-Desktop#55]
Thanks for the code! The bot works fine for ~30s, then i always get the error:

```
Python: Traceback (most recent call last):

Python:   File "./pokecli.py", line 494, in <module>
    main()
  File "./pokecli.py", line 70, in main
    bot.tick()
  File "/Users/myuser/github/PokemonGo/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/__init__.py", line 85, in tick

Python:     if worker.work() == WorkerResult.RUNNING:
  File "/Users/myuser/github/PokemonGo/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/follow_spiral.py", line 56, in work

Python:     point = self.points[self.ptr]
IndexError: list index out of range
```

Is there any solution to this? Do i have to change a config file or the walking speed etc.?

I use OSX 10.10.5, all brew and pip packages are updated (also got no errors while installing).

**Comment by geoah** [comment]
This is a bug when you don't set the step limit. Creating the spiral doesn't seem to take into account the default step limit.

Make sure you set a number for `max steps` (5 for example) and it should work.

**Comment by subzerofun** [comment]
thanks, it worked!
