### ISSUE TITLE
Error electron main.js

### ISSUE THREAD

**Issue by rednka** [PokemonGoF/PokemonGo-Bot-Desktop#58]
Hello, i have install the desktop bot on my computer, but after the success "npm install" i launch "npm start" and i have a lot of error ..

i have follow this steps: 
git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop, ok
brew install python node, (error ?), no 'brew' command detected (git bash), not ok
pip install virtualenv, ok
cd PokemonGo-Bot-Desktop, ok
npm install, ok

npm start, error

npm log.txt : 

`
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart PokemonGoBot@0.0.1-alpha
6 info start PokemonGoBot@0.0.1-alpha
7 verbose unsafe-perm in lifecycle true
8 info PokemonGoBot@0.0.1-alpha Failed to exec start script
9 verbose stack Error: PokemonGoBot@0.0.1-alpha start:`electron main.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid PokemonGoBot@0.0.1-alpha
11 verbose cwd d:\Documents and Settings\flo\PokemonGo-Bot-Desktop
12 error Windows_NT 5.1.2600
13 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error PokemonGoBot@0.0.1-alpha start:`electron main.js`
17 error Exit status 1
18 error Failed at the PokemonGoBot@0.0.1-alpha start script 'electron main.js'.
18 error This is most likely a problem with the PokemonGoBot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs PokemonGoBot
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls PokemonGoBot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

My setup : Windows XP SP3

edit : i have already search for this error on all issue, i have manual install "electron" with
`npm install electron-prebuild -g` after this, i use npm start and same error encounter.

edit2: i have clean my computer and reinstall node, python, pokemongo-bo-desktop, npm install electron, npm install, npm start etc.. and same error

**Comment by sniok** [comment]
You are using OS that is 14 years old. How do you expect anything to work on it?

**Comment by rednka** [comment]
Yes i use a bad OS and what ? i have read a same issue with OS linux, so isn't because i use windows xp and NodeJS work for me

**Comment by sniok** [comment]
Electron only supports Windows 7 or higher.

**Comment by rednka** [comment]
Ok, so bye :)
