### ISSUE TITLE
IndexError : list index out of range

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot-Desktop#60]
Hi guys so I had my bot installed for a day and everything was working fine until I left it running overnight. When I woke up it had stopped so I closed it and restarted it but since that it has kept stopping about 20 seconds are running and I am getting this 

Python: Traceback (most recent call last):
  File "./pokecli.py", line 494, in <module>

Python:     main()

Python:   File "./pokecli.py", line 70, in main
    bot.tick()
  File "/Users/hamishtugado/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/**init**.py", line 85, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/Users/hamishtugado/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/cell_workers/follow_spiral.py", line 56, in work

Python:     point = self.points[self.ptr]

Python: IndexError: list index out of range

If anybody knows how to fix this that would be great. I am on OSX Yosemite 10.10.4

**Comment by sniok** [comment]
Check out #55

**Comment by htugsdr** [comment]
Thank you so much! Appreciate it!
