### ISSUE TITLE
Java Script Error on OSX - GUI opens but doesn't continue 

### ISSUE THREAD

**Issue by Casual-User** [PokemonGoF/PokemonGo-Bot-Desktop#64]
When opening the GUI, my virtualenv Desktop-Bot doesn't read any config.json file I put into the respective folder, nor does it continue with my GUI input. I just get a crash with the message below. Any hints what might have gone wrong? Thanks and best regards!

A JavaScript error occurred in the main process

Uncaught Exception:
SyntaxError: Unexpected number in JSON at position 1408
    at Object.parse (native)
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/main.js:259:25
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:138:14
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:106:16
    at Server.onListen (/Applications/MEDIA/Programs/Pokebot/PokeMonBot Alternatives/Bot1-WoG/PokemonGo-Bot-Desktop/node_modules/portfinder/lib/portfinder.js:35:5)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)

**Comment by sniok** [comment]
This happened probably because you put custom config file.

**Comment by Casual-User** [comment]
YES. I started with a clean install without any modifications, used the GUI to insert the information – bam! Bot runs. THANK YOU! So the cloned text from the non-desktop PokemonGo-Bot regarding the config.json file was a trap ;-)
