### ISSUE TITLE
Help cant start ...

### ISSUE THREAD

**Issue by nzflex** [PokemonGoF/PokemonGo-Bot-Desktop#67]
OSX issue starting bot I get the following error.

New python executable in /Users/flex/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
(PokemonGo-Bot) macbook-pro:pokemongo-bot flex$ python pokecli.py -cf ./configs/config.json
2016-08-07 14:15:42,588 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

**Comment by ghost** [comment]
?

Haven't you heard that Niantic broke bots

**Comment by nzflex** [comment]
Havent you heard that the API has been broken ?

**Comment by ghost** [comment]
@nzflex ???
