### ISSUE TITLE
Can you update the bot with new API ?

### ISSUE THREAD

**Issue by leovarmak** [PokemonGoF/PokemonGo-Bot-Desktop#68]

**Comment by sniok** [comment]
We are working on it

**Comment by sniok** [comment]
Bot is now updated. Please update to the latest version or do a clean install

**Comment by leovarmak** [comment]
@sniok Man please generate a new release version. So non-programmers can easily access the thing

**Comment by sniok** [comment]
@leovarmak yeah this is good idea, thanks
