### ISSUE TITLE
Json file in web not working

### ISSUE THREAD

**Issue by gungoan** [PokemonGoF/PokemonGo-Bot-Desktop#7]
I  run  this  app  in windows  7,
Electron start  fine but in  /gofbot/web/
-  location-*.json (No  data json "{}")
-  inventory-*.json  (Not create)
- catchable-*.json (Not create)

I think pywin not running.

Please  fix  it

**Comment by JVenberg** [comment]
Were you able to log in and see the map?

**Comment by gungoan** [comment]
Map is running but dont focus character inventory,... in console electron missing json file  inventory-_.json and
catchable-_.jsonn

**Comment by JVenberg** [comment]
Do you have the most up to date version?

**Comment by gungoan** [comment]
I install new  version via  command:
git clone --recursive https://github.com/PokemonGoF/PokemonGo-Bot-Desktop

**Comment by JVenberg** [comment]
This is what is should look like:
![desktop](https://cloud.githubusercontent.com/assets/8976558/17208677/86e0bb3c-546e-11e6-9c7a-ba9cc81cf7de.png)
It appears you have an older version

**Comment by gungoan** [comment]
I change code in  main.js
`fs.writeFileSync(location_path,err);`

And  in  json  file show error:
`Error: ENOENT: no such file or directory, open 'E:\PokemonGo-Bot-Desktop\gofbot\web\location-**@gmail.com.json'`

![image](https://cloud.githubusercontent.com/assets/3823318/17216341/747a06e6-550a-11e6-90bb-8bb8239b908d.png)

**Comment by JVenberg** [comment]
What do you have in 'E:\PokemonGo-Bot-Desktop\gofbot\web\location-**@gmail.com.json'?
The code that you wrote added the error into the json file.
I suggest deleting the repo and recloning it again

**Comment by gungoan** [comment]
I changed to track bugs in the json file . This json print files here:
`Error: ENOENT: no such file or directory, open 'E:\PokemonGo-Bot-Desktop\gofbot\web\location-username@gmail.com.json'`

I try deleting the  repo  and  recloning  it again but same
this json file print: 
**`{}`**

**Comment by JVenberg** [comment]
Yup, it is supposed to print {}, it's only there to start the file so it can later be populated
