### ISSUE TITLE
OSX Terminal error message

### ISSUE THREAD

**Issue by NinjaStew** [PokemonGoF/PokemonGo-Bot-Desktop#70]
### Expected Behavior

Return account authorization confirmation or denial. 
### Actual Behavior

Returned error in terminal and application became stuck in loading state. 
`python ./pokecli.py
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions`
### Steps to Reproduce

Update to newest repo and attempt to launch. 
### Information
- OS
- Git commit
- App's logs

**Comment by sniok** [comment]
Same as #71
