### ISSUE TITLE
Which Map API should I get credentials for?

### ISSUE THREAD

**Issue by Roenbaeck** [PokemonGoF/PokemonGo-Bot-Desktop#72]

**Comment by Roenbaeck** [comment]
Which of the available Google Map API:s should I get credentials for? Maybe I am doing something wrong. Is there a guide to getting the correct credentials somewhere?

**Comment by Roenbaeck** [comment]
Seems like I did everything correct. At least according to this guide: https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key
However, no map is appearing and "Loading..." is displayed forever, even though I can see the bot running around to pokestops in the terminal.

**Comment by sniok** [comment]
Yeah thats the right way to get gapi key. Make sure you are running latest version, because we had similar problem fixed recently.

**Comment by Roenbaeck** [comment]
Thanks, a git pull solved the problem.
