### ISSUE TITLE
Log does not autoscroll

### ISSUE THREAD

**Issue by karllaschnikov** [PokemonGoF/PokemonGo-Bot-Desktop#74]
### Expected Behavior

Log should autoscroll to the most recent log event, in order to be able to track what the bot is doing
### Actual Behavior

Log stays at the first few lines of output
### Steps to Reproduce

start the bot :)
### Information
- OS
- Git commit
- App's logs

**Comment by sniok** [comment]
Implemented in new log system
59193da
