### ISSUE TITLE
encrypt.so issue back again

### ISSUE THREAD

**Issue by Magamar01** [PokemonGoF/PokemonGo-Bot-Desktop#76]
Python: 2016-08-07 08:42:04,664 [sentry.errors.uncaught] [ERROR] [u'OSError: dlopen(encrypt.so, 6): no suitable image found.  Did find:\n\tencrypt.so: not a file', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 440, in LoadLibrary', u'  File "ctypes/**init**.py", line 362, in **init**']

Still getting this error after installing encrypt.so. I created the encrypt.so folder in gofbot and copied libencrypt.so to gofbot/encrypt.so. Don't why I'm still receiving this error

**Comment by NinjaStew** [comment]
I was doing the same thing for a while. Instead of creating a folder named "encrypt.so", rename the libencrybt.so to encrypt.so and put it in the gofbot folder.

**Comment by Magamar01** [comment]
I see, so I don't need to create a new folder?

**Comment by sniok** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2769#issuecomment-238077548
Maybe this will help

**Comment by sniok** [comment]
Oh wait you put it in the wrong place. You need to place file encrypt.so to the gofbot folder

**Comment by Magamar01** [comment]
NinjaStew's solution worked thanks guys

**Comment by sniok** [comment]
Edited REAMDE with more clear instructions
