### ISSUE TITLE
No pokemon data showing on the map

### ISSUE THREAD

**Issue by klokklok2** [PokemonGoF/PokemonGo-Bot-Desktop#77]
For some reason there is nothing show up on my map.

The error I'm getting:

file:///C:/Users/{username}/Desktop/PikaBot-win32-ia32/resources/app/qrcode.js Failed to load resource: net::ERR_FILE_NOT_FOUND

The map is loading fine and my character walks around but there aren't any pokestops/pokemons on my map.

**Comment by sniok** [comment]
0.0.1-alpha release is not woking

**Comment by klokklok2** [comment]
Allright so this release: https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases Isn't working? I got updated 2 hours ago.

**Comment by sniok** [comment]
@klokklok2 Yep, it's not working. Also removing files so noone downloads broken version

**Comment by klokklok2** [comment]
Thanks I thought it worked for other people.
