### ISSUE TITLE
Not able to spin pokestops or catch lured pokemon.

### ISSUE THREAD

**Issue by Magamar01** [PokemonGoF/PokemonGo-Bot-Desktop#81]
Bot log states that every pokestop is out of range and it wont catch lured pokemon stating : "Possibly searching too often taking rest" This starts after 1 hour of running the bot

**Comment by douglascamata** [comment]
Not enough debug information. I'm closing this and you can reopen when you add more information.

**Comment by Magamar01** [comment]
For example

`Python: 2016-08-07 18:38:25,764 [  SpinFort] [INFO] [pokestop_out_of_range] Pokestop 2nd Street Angel out of range.

Python: 2016-08-07 18:38:25,764 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
`
It constantly gives me these two messages after running the bot for an hour, regardless of which pokestop I'm currently at

**Comment by Magamar01** [comment]
Only solution is to log out and log back in
