### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by klokklok2** [PokemonGoF/PokemonGo-Bot-Desktop#82]
After launching to he login screen I'm ending up with this error in my console:

module.js:442 Uncaught Error: Cannot find module 'request'

request ends up being undefined

**Comment by sniok** [comment]
Any other problem besides one error in console?

**Comment by klokklok2** [comment]
Yes sorry I'm unable to login because of this error. When trying to login it needs data from request.

**Comment by tnsbm** [comment]
Please reopen if error still persists
