### ISSUE TITLE
［enhancement］Show more stat info

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot-Desktop#84]
It would be more clear if it can show more on the stat page.
- how many pokemon in inventory (at the moment)
- how many items in inventory (total number)
- how many were caught (since login)
- how many were released (since login)
- how many exp earned (since login)
- how many eggs were hatched (since login)

I know there is no API for this. But we can add a function to count the corresponding events from the terminal's log.

**Comment by sniok** [comment]
Implemented in 0f72c2a

**Comment by ghost** [comment]
@sniok does it work the same way of "UpdateTitleStats" ? can I set what I wanna see?

**Comment by sniok** [comment]
What is "UpdateTitleStats"?

**Comment by ghost** [comment]
one of the bot's plugins/tasks
ex:
`{
            "type": "UpdateTitleStats",
            "config": {
                "min_interval": 15,
                "stats": [
                    "stardust_earned",
                    "xp_earned",
                    "xp_per_hour"
                ]
            }
        },`

**Comment by sniok** [comment]
No, it's not using that worker

**Comment by sniok** [comment]
Closing this
