### ISSUE TITLE
How to fix issues. 

### ISSUE THREAD

**Issue by teezanateep1** [PokemonGoF/PokemonGo-Bot-Desktop#86]
Bot exited unexpectedly. Restarting in 5 secs
Bot path: /Users/OuBdw/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by ghost** [comment]
try

```
virtualenv .
source bin/activate
pip install -r requirements.txt
```

**Comment by BramHoey** [comment]
I have the some issue, running pokecli.py its self works for me. I guess the problem is in the desktop version.

**Comment by BoGnY** [comment]
#51 give you the solution.. problem is in main.js that set python command on windows system in the pywin dir, overriding the PATH var on windows, that don't have lib and modules installed..
just comment line 174, 175 and 176 on main.js

;)

**Comment by faegan** [comment]
> just comment line 174, 175 and 176 on main.js

var pythonCmd = 'python';
  //if (os.platform() == 'win32') {
  //  pythonCmd = path.join('C:/', 'pywin', 'python.exe');
  //}

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
