### ISSUE TITLE
pikabot application keep refreshing

### ISSUE THREAD

**Issue by spdragon** [PokemonGoF/PokemonGo-Bot-Desktop#87]
after npm start, the pikabot show up but it keep refreshing and i can't do anything on pikabot, the bot also doesn't seem working

**Comment by sniok** [comment]
Have you installed encrypt.so ?

**Comment by spdragon** [comment]
no, i cant run the code, cmd say wget is not recognized as an internal or external command
i'm using window

**Comment by sniok** [comment]
You need to find tutorial how to get encrypt library on windows
