### ISSUE TITLE
Map will not load

### ISSUE THREAD

**Issue by siembz** [PokemonGoF/PokemonGo-Bot-Desktop#88]
Hello

Im using mac and the map will not load. any suggestions ?

"Google map was not loaded correctly"

![skjermbilde 2016-08-08 kl 15 06 22](https://cloud.githubusercontent.com/assets/20815623/17480770/d1976b9e-5d79-11e6-918b-9e107ba3cf72.png)

**Comment by sniok** [comment]
Please provide more information 

### Information
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by siembz** [comment]
@sniok i turned on java on google api and it works now
