### ISSUE TITLE
Bot delete encrypt.dll after button selection

### ISSUE THREAD

**Issue by BoGnY** [PokemonGoF/PokemonGo-Bot-Desktop#93]
### Expected Behavior

Bot running
### Actual Behavior

Bot delete encrypt.dll after button selection
### Steps to Reproduce

After installation, put encrypt.dll on gofbot then select it with button to select encrypt file.. 
The dll is now deleted...
If I put another times encrypt.dll WITHOUT select it with button, bot work perfect..

I try 4 times, and every times the select button delete my encrypt.dll file...
### Information
- OS: Windows 10 64bit
- Git commit: a7a7a1de1ed8902e2a5630b226c2eaf7617ff15f
- App's logs:

> 2016-08-09 12:00:52,973 [PokemonGoBot] [INFO]
> 
> Python: 2016-08-09 12:00:52,973 [PokemonGoBot] [ERROR] encrypt.dll is not found! Please place it in the bots root directory or set libencrypt_location in config.
> 2016-08-09 12:00:52,973 [PokemonGoBot] [INFO] Platform: win32 Encrypt.so directory: C:\Luca\PokemonGO\bot_desktop\gofbot
> 
> Bot exited

**Comment by sniok** [comment]
@JVenberg

**Comment by Outpox** [comment]
@BoGnY : Where did you saved `encrypt.dll` ? Inside the `PokemonGo-Bot-Desktop` folder or outside ?
Also, do you have an `encrypt.so` file in `PokemonGo-Bot-Desktop/gofbot/` ?

**Comment by BoGnY** [comment]
I saved `encrypt.dll` in `PokemonGo-Bot-Desktop\gofbot` and I put it here because is needed by bot..
And no, I don't have any `encrypt.so` file because I'm on Windows system.

I override the selection button by adding `"libencrypt_location": ".\\encrypt.dll"` in my `config.json` file, so bot find `encrypt.dll` in the correct path where I put it..

**Comment by Outpox** [comment]
I just tried on a Windows computer and the file isn't deleted, a copy is made inside the gofbot/ folder, that's all.
You should `git pull` the repo, I made a PR (#100) which was merged and which tells you when the file is present.
