### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by wharvie57** [PokemonGoF/PokemonGo-Bot-Desktop#94]
Starting Python process...
Bot path: /Users/stream/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Python: Traceback (most recent call last):
  File "./pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

Bot exited

This appears and I don't know how to fix it! 
Im on a Mac and Ive set up everything!

**Comment by wharvie57** [comment]
FIxed it but now its says this when i get to the bot screen "2016-08-09 12:11:04,330 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory or set libencrypt_location in config.
2016-08-09 12:11:04,330 [PokemonGoBot] [INFO] Platform: darwin Encrypt.so directory: /Users/stream/PokemonGo-Bot-Desktop/gofbot"

**Comment by sniok** [comment]
You need encrypt.so

**Comment by rickycc** [comment]
@wharvie57 Download and use it
[http://www.mediafire.com/download/engnf5fvj65duxa/encrypt.so](url)

**Comment by OscarToV** [comment]
How did you solve the first error?

**Comment by Outpox** [comment]
@OscarToV most likely with:  
`pip install -r requirements.txt` 
or
`pip install --upgrade -r requirements.txt`

**Comment by OscarToV** [comment]
@Outpox  thanks!

**Comment by CodeCompiler** [comment]
having the same issue on windows

pip install requirements all went well with no error

 encrypt.dll is present in root as well as under gofbot dir

**Comment by fdxfdcfd** [comment]
@Outpox 
I run sudo pip install --upgrade -r requirements.txt or pip install -r requirements.txt
and get:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YwdSHF/protobuf-to-dict/

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
