### ISSUE TITLE
Ideas For Improvement!!!!!!

### ISSUE THREAD

**Issue by wharvie57** [PokemonGoF/PokemonGo-Bot-Desktop#97]
Since this is the most wonderful bot ever and catches the most pokemon ever I say that since we catch so many pokemon that we fill up or bag! WELL I think it would be wonderful if the devs could add a feature that insta transfers alot of pokemon like it would ask which type of pokemon to transfer and say you said pidgeys! then it would ask how many and you would choose!!

Would be awesome if you did this in the next update!

Luv and more luv to the devs!

**Comment by sniok** [comment]
This is already a feature. You can configure your config.json file using this manual https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files
