### ISSUE TITLE
pokestops

### ISSUE THREAD

**Issue by instinctkev** [PokemonGoF/PokemonGo-Bot-Desktop#99]
just wondering, why my bot keeps saying no pokestops found in your area? and also it kept saying the distance area is too small? what would be the setting? please guide me. thanks

**Comment by Outpox** [comment]
This has nothing to do with this app since it's just a wrapper around the bot. You should search the bot [repository instead](https://github.com/PokemonGoF/PokemonGo-Bot/issues).

**Comment by tnsbm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues/138
